import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { generateProgram, computeAutoSchedule } from '../engine/algorithm';
import { WORKOUT_SPIKE_REWARD } from '../engine/chestEngine';
import { Alert } from 'react-native';

// Lazy-import to avoid circular deps at module init time
const getSync = () => {
  const { uploadToCloud } = require('../services/syncService');
  return { uploadToCloud };
};
const getAuthUser = () => {
  try {
    const { useAuthStore } = require('./useAuthStore');
    return useAuthStore.getState().user;
  } catch {
    return null;
  }
};

/** Push current store state to Firestore for signed-in (non-anonymous) users. */
async function syncIfAuthenticated(state) {
  const user = getAuthUser();
  if (!user || user.isAnonymous) return;
  try {
    const { uploadToCloud } = getSync();
    await uploadToCloud(user.uid, state);
  } catch (_) {
    // Silently ignore offline / permission errors
  }
}

export const useAppStore = create(
  persist(
    (set, get) => ({
      isOnboarded: false,
      profile: {
        name: '',
        age: 25,
        height: 185,
        weight: 80,
        units: 'metric',
        goal: 'vertical',
        equipment: 'bodyweight',
        level: 'intermediate',
        history: [], // array of strings like 'jumper_knee'
        schedule: 'auto', // 'auto' or { '1': 'workout', '2': 'rest', '3': 'match', ... }
        daysPerWeek: 3,
        matchDays: [],
        timePerDay: 45
      },
      stats: {
        sessionsCompleted: 0,
        currentPhaseId: 'A', // A, B, or C
        streak: 0,
        lastWorkoutDate: null
      },
      workoutPhases: [], // Array of objects mapping to A, B, C generated by algorithm
      weightLogs: {}, // Record of { date, weight } arrays for trackable exercises
      workoutHistory: [], // Array of YYYY-MM-DD strings for calendar checking
      language: 'nl', // Active language ('nl' Dutch default, 'en' English)

      // Fun Mode
      mode: 'serious', // 'serious' | 'fun'
      spikes: 0,       // Volleyball-themed currency earned by completing workouts
      inventory: [],   // Array of item IDs the user owns
      chest_opens: 0,  // Total chests opened (for stats)
      equipped: {      // Currently equipped items per category
        ball: null,
        court: null,
        hall: null,
        jersey: null,
        players: [],   // up to 6 player item IDs
      },

      // Notifications
      notifications: {
        workoutRemindersEnabled: false,
        streakRemindersEnabled: false,
      },

      // Actions
      toggleWorkoutReminders: async (enabled) => {
        set((state) => ({
          notifications: { ...state.notifications, workoutRemindersEnabled: enabled }
        }));
        const { scheduleDailyWorkoutReminder, cancelWorkoutReminders } = require('../services/notificationService');
        if (enabled) {
          await scheduleDailyWorkoutReminder();
        } else {
          await cancelWorkoutReminders();
        }
        syncIfAuthenticated({ ...get() });
      },
      toggleStreakReminders: (enabled) => {
        set((state) => ({
          notifications: { ...state.notifications, streakRemindersEnabled: enabled }
        }));
        syncIfAuthenticated({ ...get() });
      },

      completeOnboarding: (newProfile) => {
        // Run the AI engine to generate the DUP phases based on constraints
        let customItems = [];
        try {
          const { useSocialStore } = require('./useSocialStore');
          customItems = [...useSocialStore.getState().customExercises, ...useSocialStore.getState().downloadedExercises];
        } catch (_) {}
        const phases = generateProgram(newProfile, customItems);
        
        const newState = { 
          profile: newProfile, 
          isOnboarded: true,
          workoutPhases: phases,
          stats: {
            sessionsCompleted: 0,
            currentPhaseId: 'A', // Always start at Phase A
            streak: 0,
            lastWorkoutDate: null
          }
        };
        set(newState);
        syncIfAuthenticated({ ...get(), ...newState });
      },
      
      finishWorkout: (currentWeights) => {
        const { stats, weightLogs, workoutPhases, workoutHistory, profile, language } = get();
        const activePhase = workoutPhases.find(p => p.id === stats.currentPhaseId);
        
        // Log weights and Apply Progressive Overload
        const newLogs = { ...weightLogs };
        const today = new Date();
        const ymd = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
        
        Object.entries(currentWeights).forEach(([exId, weight]) => {
          if (!newLogs[exId]) newLogs[exId] = [];
          
          const rawWeight = parseFloat(weight) || 0;
          let suggestedNext = rawWeight;

          if (newLogs[exId].length > 0) {
            const lastLog = newLogs[exId][newLogs[exId].length - 1];
            if (lastLog && parseFloat(lastLog.weight) === rawWeight && rawWeight > 0) {
               suggestedNext = rawWeight + 2.5; 
            }
          }

          newLogs[exId].push({ date: today.toLocaleDateString(), weight: suggestedNext });
        });

        // Add to calendar history
        const newHistory = [...workoutHistory];
        if (!newHistory.includes(ymd)) {
          newHistory.push(ymd);
        }

        // --- Streak Logic ---
        let newStreak = stats.streak;
        
        if (!stats.lastWorkoutDate) {
           newStreak = 1;
        } else if (stats.lastWorkoutDate === ymd) {
           // Already worked out today
           newStreak = stats.streak;
        } else {
           // Calculate difference in days, ignoring time
           const lastDate = new Date(stats.lastWorkoutDate);
           lastDate.setHours(0,0,0,0);
           const todayZero = new Date(today);
           todayZero.setHours(0,0,0,0);
           const diffTime = Math.abs(todayZero - lastDate);
           const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 
           
           const activeSchedule = profile.schedule === 'auto' || !profile.schedule 
              ? computeAutoSchedule(profile.daysPerWeek || 3, profile.matchDays || []) 
              : profile.schedule;

           // Schedule-based: Check if there were any 'workout' or 'match' days missed in between
           // If diffDays > 1, we need to inspect the days in between
           let missedMandatoryDay = false;
           if (diffDays > 1) {
              for (let i = 1; i < diffDays; i++) {
                 const checkDate = new Date(lastDate);
                 checkDate.setDate(checkDate.getDate() + i);
                 // getDay: 0 = Sun, 1 = Mon ... 6 = Sat
                 // Our schedule uses 1 for Mon, 7 for Sun
                 let dayNum = checkDate.getDay();
                 if (dayNum === 0) dayNum = 7;
                 
                 const dayType = activeSchedule[dayNum.toString()];
                 if (dayType === 'workout' || dayType === 'match') {
                    missedMandatoryDay = true;
                    break;
                 }
              }
           }
           
           if (missedMandatoryDay) {
              newStreak = 1; // Reset
           } else {
              newStreak += 1; // Continued streak
           }
        }
        
        let inventoryAdditions = [];
        let spikeAdditions = get().mode === 'fun' ? WORKOUT_SPIKE_REWARD : 0;
        let streakMessage = null;

        if (get().mode === 'fun' && newStreak > stats.streak && newStreak > 0) {
           // Check milestones
           const milestones = [
              { days: 7, msg: { nl: '7 Dagen Streak! Je kreeg 50 Spikes.', en: '7 Day Streak! You got 50 Spikes.' }, spikes: 50 },
              { days: 30, msg: { nl: '30 Dagen Streak! Epische speler ontgrendeld!', en: '30 Day Streak! Epic player unlocked!' }, items: ['p_captain_epic'] },
              { days: 100, msg: { nl: '100 Dagen Streak! MYTHISCHE BAL ontgrendeld!', en: '100 Day Streak! MYTHIC BALL unlocked!' }, items: ['ball_dragon_mythic'] },
              { days: 200, msg: { nl: '200 Dagen Streak! MYTHISCH VELD ontgrendeld!', en: '200 Day Streak! MYTHIC COURT unlocked!' }, items: ['court_ethereal_mythic'] },
              { days: 300, msg: { nl: '300 Dagen Streak! MYTHISCH TENUE ontgrendeld!', en: '300 Day Streak! MYTHIC KIT unlocked!' }, items: ['jersey_diamond_mythic'] },
              { days: 400, msg: { nl: '400 Dagen Streak! MYTHISCHE ZAAL ontgrendeld!', en: '400 Day Streak! MYTHIC HALL unlocked!' }, items: ['hall_temple_mythic'] },
              { days: 500, msg: { nl: '500 Dagen Streak! VOLLEYBAL GOD ontgrendeld!', en: '500 Day Streak! VOLLEYBALL GOD unlocked!' }, items: ['p_god_mythic'] },
           ];
           
           const hit = milestones.find(m => m.days === newStreak);
           if (hit) {
              streakMessage = hit.msg[language] || hit.msg.en;
              if (hit.spikes) spikeAdditions += hit.spikes;
              if (hit.items) {
                 hit.items.forEach(itemId => {
                    if (!get().inventory.includes(itemId)) {
                       inventoryAdditions.push(itemId);
                    }
                 });
              }
           } else {
              // Normal streak bonus
              spikeAdditions += 5; // small bonus for keeping streak
           }
        }

         if (streakMessage) {
           setTimeout(() => Alert.alert('Streak Milestone!', streakMessage), 1000);
           if (get().notifications.streakRemindersEnabled) {
              const { sendImmediateNotification } = require('../services/notificationService');
              sendImmediateNotification('Streak Milestone!', streakMessage);
           }
         }

         // Schedule next workout reminder if enabled
         if (get().notifications.workoutRemindersEnabled) {
            const { scheduleDailyWorkoutReminder } = require('../services/notificationService');
            scheduleDailyWorkoutReminder();
         }

         // Advance phase A -> B -> C -> A
         const nextPhaseId = stats.currentPhaseId === 'A' ? 'B' : stats.currentPhaseId === 'B' ? 'C' : 'A';

        const newState = {
          weightLogs: newLogs,
          workoutHistory: newHistory,
          stats: {
            ...stats,
            sessionsCompleted: stats.sessionsCompleted + 1,
            currentPhaseId: nextPhaseId,
            streak: newStreak,
            lastWorkoutDate: ymd
          },
          spikes: get().spikes + spikeAdditions,
          inventory: [...get().inventory, ...inventoryAdditions]
        };
        set(newState);
        syncIfAuthenticated({ ...get(), ...newState });
        
        // Update social profile with new streak so it syncs to cloud
        setTimeout(() => {
           try {
              const { useSocialStore } = require('./useSocialStore');
              if (useSocialStore.getState().isPublicProfile) {
                 const { updatePublicProfile } = require('../services/socialService');
                 const user = getAuthUser();
                 if (user) {
                    const pubData = {
                       displayName: profile.name || user.displayName,
                       streak: newStreak,
                       level: profile.level,
                       spikes: get().spikes + spikeAdditions,
                       goal: profile.goal
                    };
                    updatePublicProfile(user.uid, pubData, true);
                 }
              }
           } catch(e) {}
        }, 500);
      },

      wipeData: () => {
        const cleared = {
          isOnboarded: false,
          profile: {},
          stats: { sessionsCompleted: 0, currentPhaseId: 'A', streak: 0, lastWorkoutDate: null },
          workoutPhases: [],
          weightLogs: {},
          workoutHistory: [],
          mode: 'serious',
          spikes: 0,
          inventory: [],
          chest_opens: 0,
          equipped: { ball: null, court: null, hall: null, jersey: null, players: [] },
          notifications: { workoutRemindersEnabled: false, streakRemindersEnabled: false },
        };
        set(cleared);
        syncIfAuthenticated(cleared);
      },

      /** Load cloud data into the store (called after Google sign-in). */
      hydrateFromCloud: (data) => {
        // Only set known keys to avoid polluting the store
        const safeData = {};
        const allowed = [
          'isOnboarded', 'profile', 'stats', 'workoutPhases',
          'weightLogs', 'workoutHistory', 'language', 'mode',
          'spikes', 'inventory', 'chest_opens', 'equipped', 'notifications'
        ];
        allowed.forEach((k) => {
          if (k in data) safeData[k] = data[k];
        });
        set(safeData);

        // Hydrate social data if present
        try {
          const { useSocialStore } = require('./useSocialStore');
          const socialData = {};
          ['isPublicProfile', 'following', 'customExercises', 'downloadedExercises'].forEach(k => {
            if (k in data) socialData[k] = data[k];
          });
          if (Object.keys(socialData).length > 0) {
            useSocialStore.setState(socialData);
          }
        } catch (_) {}
      },

      setLanguage: (lang) => {
        set({ language: lang });
        syncIfAuthenticated({ ...get(), language: lang });
      },
      setMode: (mode) => {
        set({ mode });
        syncIfAuthenticated({ ...get(), mode });
      },
      awardSpikes: (amount) => set(state => ({ spikes: state.spikes + amount })),
      spendSpikes: (amount) => set(state => ({ spikes: Math.max(0, state.spikes - amount) })),
      addToInventory: (itemId) => set(state => ({
        inventory: state.inventory.includes(itemId) ? state.inventory : [...state.inventory, itemId],
        chest_opens: state.chest_opens + 1,
      })),
      equipItem: (itemId, category) => set(state => {
        if (category === 'player') {
          const players = state.equipped.players || [];
          const alreadyEquipped = players.includes(itemId);
          const newPlayers = alreadyEquipped
            ? players.filter(id => id !== itemId)   // unequip
            : [...players.slice(0, 5), itemId];      // equip (max 6)
          return { equipped: { ...state.equipped, players: newPlayers } };
        }
        const isAlreadyEquipped = state.equipped[category] === itemId;
        return { equipped: { ...state.equipped, [category]: isAlreadyEquipped ? null : itemId } };
      }),
    }),
    {
      name: 'volleybuild-storage', // name of the item in the storage (must be unique)
      storage: createJSONStorage(() => AsyncStorage), 
    }
  )
);
