import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { generateProgram } from '../engine/algorithm';
import { WORKOUT_SPIKE_REWARD } from '../engine/chestEngine';

export const useAppStore = create(
  persist(
    (set, get) => ({
      isOnboarded: false,
      profile: {
        name: '',
        age: 25,
        height: 185,
        weight: 80,
        units: 'metric',
        goal: 'vertical',
        equipment: 'bodyweight',
        level: 'intermediate',
        history: [], // array of strings like 'jumper_knee'
        daysPerWeek: 3,
        timePerDay: 45
      },
      stats: {
        sessionsCompleted: 0,
        currentPhaseId: 'A' // A, B, or C
      },
      workoutPhases: [], // Array of objects mapping to A, B, C generated by algorithm
      weightLogs: {}, // Record of { date, weight } arrays for trackable exercises
      workoutHistory: [], // Array of YYYY-MM-DD strings for calendar checking
      language: 'nl', // Active language ('nl' Dutch default, 'en' English)

      // Fun Mode
      mode: 'serious', // 'serious' | 'fun'
      spikes: 0,       // Volleyball-themed currency earned by completing workouts
      inventory: [],   // Array of item IDs the user owns
      chest_opens: 0,  // Total chests opened (for stats)

      // Actions
      completeOnboarding: (newProfile) => {
        // Run the AI engine to generate the DUP phases based on constraints
        const phases = generateProgram(newProfile);
        
        set({ 
          profile: newProfile, 
          isOnboarded: true,
          workoutPhases: phases,
          stats: {
            sessionsCompleted: 0,
            currentPhaseId: 'A' // Always start at Phase A
          }
        });
      },
      
      finishWorkout: (currentWeights) => {
        const { stats, weightLogs, workoutPhases, workoutHistory } = get();
        const activePhase = workoutPhases.find(p => p.id === stats.currentPhaseId);
        
        // Log weights and Apply Progressive Overload
        const newLogs = { ...weightLogs };
        const today = new Date().toLocaleDateString();
        Object.entries(currentWeights).forEach(([exId, weight]) => {
          if (!newLogs[exId]) newLogs[exId] = [];
          
          const rawWeight = parseFloat(weight) || 0;
          let suggestedNext = rawWeight;

          // Progressive Overload Logic: 
          // If the user hit this exact weight successfully in the previous session as well,
          // suggest they increase the load by 2.5 (kg/lbs) next time.
          if (newLogs[exId].length > 0) {
            const lastLog = newLogs[exId][newLogs[exId].length - 1];
            if (lastLog && parseFloat(lastLog.weight) === rawWeight && rawWeight > 0) {
               suggestedNext = rawWeight + 2.5; 
            }
          }

          newLogs[exId].push({ date: today, weight: suggestedNext });
        });

        // Advance phase A -> B -> C -> A
        const nextPhaseId = stats.currentPhaseId === 'A' ? 'B' : stats.currentPhaseId === 'B' ? 'C' : 'A';

        // Add to calendar history
        const d = new Date();
        const ymd = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
        const newHistory = [...workoutHistory];
        if (!newHistory.includes(ymd)) {
          newHistory.push(ymd);
        }

        set({
          weightLogs: newLogs,
          workoutHistory: newHistory,
          stats: {
            ...stats,
            sessionsCompleted: stats.sessionsCompleted + 1,
            currentPhaseId: nextPhaseId
          },
          // Award Spikes in Fun Mode
          ...(get().mode === 'fun' ? { spikes: get().spikes + WORKOUT_SPIKE_REWARD } : {}),
        });
      },

      wipeData: () => set({
        isOnboarded: false,
        profile: {},
        stats: { sessionsCompleted: 0, currentPhaseId: 'A' },
        workoutPhases: [],
        weightLogs: {},
        workoutHistory: [],
        mode: 'serious',
        spikes: 0,
        inventory: [],
        chest_opens: 0,
      }),

      setLanguage: (lang) => set({ language: lang }),
      setMode: (mode) => set({ mode }),
      awardSpikes: (amount) => set(state => ({ spikes: state.spikes + amount })),
      spendSpikes: (amount) => set(state => ({ spikes: Math.max(0, state.spikes - amount) })),
      addToInventory: (itemId) => set(state => ({
        inventory: state.inventory.includes(itemId) ? state.inventory : [...state.inventory, itemId],
        chest_opens: state.chest_opens + 1,
      })),
    }),
    {
      name: 'volleybuild-storage', // name of the item in the storage (must be unique)
      storage: createJSONStorage(() => AsyncStorage), 
    }
  )
);
