export const EXERCISES = {
  // --- TABLE 1: Lower Body Strength and Explosiveness (Vertical Jump Focus) ---
  goblet_squat: {
    id: 'goblet_squat',
    name: 'Dumbbell Goblet Squat',
    category: 'vertical_jump',
    equipment: 'dumbbell',
    muscles: ['Quadriceps', 'Gluteus Maximus', 'Core Stabilizers'],
    purpose: 'Develops foundational bilateral lower body strength, improves hip mobility, and ingrains proper squat mechanics necessary for jumping.',
    execution: 'Hold one dumbbell vertically against the chest. Descend until thighs are parallel to the floor. Drive explosively through heels to ascend.',
    sets: '3-4',
    reps: '8-12',
    impact: 'medium',
    unilateral: false,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=MeIiIdhvXT4',
  },
  bulgarian_split_squat: {
    id: 'bulgarian_split_squat',
    name: 'Dumbbell Bulgarian Split Squat',
    category: 'vertical_jump',
    equipment: 'dumbbells',
    muscles: ['Quadriceps', 'Gluteus Medius', 'Hamstrings'],
    purpose: 'Corrects unilateral strength imbalances between limbs; places a heavy emphasis on single-leg stabilization and proprioception.',
    execution: 'Elevate the rear foot on a chair or box. Hold dumbbells at sides. Lower hips until the front thigh is parallel to the ground.',
    sets: '3',
    reps: '6-10/leg',
    impact: 'low', // Great for knee issues compared to bilateral heaviness
    unilateral: true,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
  },
  rdl: {
    id: 'rdl',
    name: 'Dumbbell Romanian Deadlift (RDL)',
    category: 'vertical_jump',
    equipment: 'dumbbells',
    muscles: ['Hamstrings', 'Gluteus Maximus', 'Erector Spinae'],
    purpose: 'Strengthens the posterior chain for aggressive hip extension power during the jump and eccentric deceleration during landing.',
    execution: 'Hinge at the hips with soft knees, lowering dumbbells down the shins. Squeeze glutes aggressively to return to a standing position.',
    sets: '3',
    reps: '8-12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
  },
  dumbbell_squat_jump: {
    id: 'dumbbell_squat_jump',
    name: 'Dumbbell Squat Jumps',
    category: 'vertical_jump',
    equipment: 'dumbbells', // Light
    muscles: ['Fast-Twitch Quadriceps', 'Calves'],
    purpose: 'Bridges maximum strength and explosive power; enhances the rate of force development (RFD) under mild resistance.',
    execution: 'Hold light dumbbells at sides. Perform a rapid quarter squat and explode vertically. Land softly, absorb the force, and immediately reset.',
    sets: '3',
    reps: '5',
    impact: 'high',
    unilateral: false,
    trackable: true, // Based on dumbbell weight used
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=A-cFYWvaHr0',
  },
  approach_box_jump: {
    id: 'approach_box_jump',
    name: 'Approach Box Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight', // plus sturdy box
    muscles: ['Total Lower Body Kinetic Chain'],
    purpose: 'The most highly sport-specific jump training available. Replicates exact approach mechanics and arm swing timing.',
    execution: 'Perform a traditional 3-step volleyball approach (Left-Right-Left for right-handed hitters) and jump onto a 12-20" box. Step down carefully to reset.',
    sets: '4',
    reps: '4-6',
    impact: 'medium', // Eccentric landing force is removed because of the box
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=52FZ-8tjAis',
  },
  tuck_jumps: {
    id: 'tuck_jumps',
    name: 'Tuck Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Hip Flexors', 'Core', 'Quadriceps'],
    purpose: 'Enhances reactive stretch-shortening cycle power and trains rapid hip flexion, essential for hang time.',
    execution: 'Jump vertically, rapidly driving the knees toward the chest. Land softly and immediately bound into the next repetition with minimal ground contact.',
    sets: '3',
    reps: '8',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg'
  },
  single_leg_calf_raise: {
    id: 'single_leg_calf_raise',
    name: 'Single-Leg Calf Raises',
    category: 'vertical_jump',
    equipment: 'dumbbell',
    muscles: ['Gastrocnemius', 'Soleus'],
    purpose: 'Increases ankle plantarflexion power for the critical final push-off phase of the vertical leap.',
    execution: 'Hold one dumbbell, stand on one leg on an elevated edge. Drop the heel below parallel, then press maximally up onto the toes.',
    sets: '3',
    reps: '15-20/leg',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=_XdMSO_qI38',
  },

  // --- TABLE 2: Upper Body Power and Core Stability (Attacking Mechanics) ---
  dumbbell_shoulder_press: {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Anterior and Medial Deltoid', 'Triceps'],
    purpose: 'Builds foundational overhead pressing strength and shoulder stability, directly correlating to spiking power and blocking rigidity.',
    execution: 'Sit or stand with an engaged core. Press dumbbells from shoulder level to full lockout overhead. Control the eccentric lowering phase.',
    sets: '3',
    reps: '6-10',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
  },
  explosive_pushups: {
    id: 'explosive_pushups',
    name: 'Explosive Push-Ups',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Pectoralis Major', 'Anterior Deltoid'],
    purpose: 'Develops fast-twitch muscle fibers in the chest and anterior shoulder for high-velocity arm swings.',
    execution: 'Lower the chest to the floor, then press up with maximum explosive force, attempting to lift the hands completely off the floor.',
    sets: '3',
    reps: 'Max',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=WbCVlWuHR0A',
  },
  bent_over_rows: {
    id: 'bent_over_rows',
    name: 'Bent-Over Dumbbell Rows',
    category: 'attacking_mechanics', // also acts as prehab
    equipment: 'dumbbells',
    muscles: ['Latissimus Dorsi', 'Rhomboids', 'Biceps'],
    purpose: 'Provides critical antagonistic balance to spiking; decelerates the arm swing safely and stabilizes the scapula.',
    execution: 'Hinge forward, maintaining a flat, neutral spine. Pull dumbbells to the hip crease, squeezing the shoulder blades tightly together.',
    sets: '3',
    reps: '10-12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=roCP6wCXPqo',
  },
  dead_bug: {
    id: 'dead_bug',
    name: 'Dead Bug',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Transverse Abdominis', 'Core Stabilizers'],
    purpose: 'Enhances anti-extension core stability, preventing dangerous lower back hyperextension during the arching phase of a spike.',
    execution: 'Lie supine with arms and legs elevated. Slowly lower the opposite arm and leg to the floor without allowing the lower back to arch off the ground.',
    sets: '2',
    reps: '12/side',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'CoreSvg',
    videoUrl: 'https://www.youtube.com/watch?v=4XLEnwUr1d8',
  },
  forearm_plank: {
    id: 'forearm_plank',
    name: 'Forearm Plank',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Total Core', 'Rectus Abdominis'],
    purpose: 'Builds isometric core endurance, allowing for improved kinetic transfer from the lower body to the hitting arm.',
    execution: 'Support the body on forearms and toes, maintaining a rigid, straight line from the head to the heels. Breathe steadily.',
    sets: '3',
    reps: '45-60s',
    impact: 'low',
    unilateral: false,
    trackable: false, // Or track time
    visual: 'CoreSvg',
    videoUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
  },

  // --- TABLE 3: Multidirectional Agility and Court Speed ---
  skater_jumps: {
    id: 'skater_jumps',
    name: 'Skater Jumps',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Gluteus Medius', 'Adductors', 'Ankles'],
    purpose: 'Elite drill for lateral force production, hip stability, and single-leg deceleration strength.',
    execution: 'Bound laterally from the right leg to the left leg, absorbing the landing deeply into a partial squat. Pause to stabilize, then bound back.',
    sets: '3',
    reps: '8/side',
    impact: 'medium',
    unilateral: true,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=xPt5eMJoikk',
  },
  lateral_hurdle_hops: {
    id: 'lateral_hurdle_hops',
    name: 'Lateral Hurdle Hops',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Calves', 'Quadriceps', 'Ankles'],
    purpose: 'Trains extremely rapid ground contact times and lateral change of direction speed.',
    execution: 'Set up a line of small obstacles. Keep feet together and bounce laterally over the obstacles as quickly as possible without losing balance.',
    sets: '3',
    reps: '30s',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=Ue3Kh3LKWQM',
  },
  t_cone_drill: {
    id: 't_cone_drill',
    name: 'T-Cone Agility Drill',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Total Lower Body'],
    purpose: 'Practices the rapid transitions between sprinting, defensive shuffling, and backpedaling.',
    execution: 'Sprint forward 10m to the center cone, shuffle left 5m, shuffle right 10m, shuffle left 5m back to center, then backpedal to the start.',
    sets: '4-6',
    reps: '1',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=6Yr2IQXUGGU',
  },
  block_jump_shuffle: {
    id: 'block_jump_shuffle',
    name: 'Block Jump to Lateral Shuffle',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Calves', 'Hip Abductors'],
    purpose: 'Perfectly mimics a middle blockers movement requirements along the net during a rally.',
    execution: 'Perform a maximum vertical block jump. Upon landing, immediately execute two rapid lateral shuffles to the right, then jump again. Repeat to the left.',
    sets: '4',
    reps: '6 jumps',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=WxRIFVAGh-o',
  },

  // --- TABLE 4: Shoulder Prehabilitation and Scapular Control ---
  side_lying_external_rotation: {
    id: 'side_lying_external_rotation',
    name: 'Side-Lying External Rotation',
    category: 'shoulder_prehab',
    equipment: 'dumbbell',
    muscles: ['Infraspinatus', 'Teres Minor'],
    purpose: 'Isolates and strengthens the external rotators to counter spiking imbalances and prevent impingement syndrome.',
    execution: 'Lie on side. Pin the working elbow to the ribs at a 90-degree angle. Rotate the dumbbell upward toward the ceiling in a controlled arc.',
    sets: '3',
    reps: '10-15',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=s9TBeBHmPf8',
  },
  side_lying_flexion: {
    id: 'side_lying_flexion',
    name: 'Side-Lying Flexion',
    category: 'shoulder_prehab',
    equipment: 'dumbbell',
    muscles: ['Anterior Deltoid', 'Rotator Cuff'],
    purpose: 'Strengthens the rotator cuff through a safe, planar arc of motion, building endurance in the stabilizers.',
    execution: 'Lie on side. Keep the arm entirely straight and raise the dumbbell in an arc in front of the body, ensuring the weight stays above the torso plane.',
    sets: '3',
    reps: '10-15',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg'
  },
  prone_ytw: {
    id: 'prone_ytw',
    name: 'Prone Y-T-W Raises',
    category: 'shoulder_prehab',
    equipment: 'bodyweight', // or extremely light
    muscles: ['Lower and Mid Trapezius', 'Rhomboids'],
    purpose: 'Establishes crucial scapular retraction and depression, correcting the forward shoulder posture typical of attackers.',
    execution: 'Lie face down. Raise straight arms to form a "Y" shape, squeezing the blades together. Repeat for "T" and "W" arm positions.',
    sets: '3',
    reps: '10 each',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=AEd5OglxwPw',
  },
  pushup_plus: {
    id: 'pushup_plus',
    name: 'Push-Up Plus',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Serratus Anterior'],
    purpose: 'Prevents scapular winging; an essential movement for ensuring healthy upward rotation of the shoulder blade during overhead extension.',
    execution: 'Ascend to the top of a standard push-up. From there, push the floor away further, actively rounding the upper back to spread the shoulder blades apart.',
    sets: '3',
    reps: '12',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=O9ZGIAeHzVE',
  },
  full_can_raise: {
    id: 'full_can_raise',
    name: 'Full Can Raise (Supraspinatus)',
    category: 'shoulder_prehab',
    equipment: 'dumbbells',
    muscles: ['Supraspinatus'],
    purpose: 'Activates the superior rotator cuff muscle responsible for initiating arm abduction and centering the humeral head.',
    execution: 'Stand tall. Raise dumbbells outward at a 45-degree angle (in the scapular plane) with thumbs pointing strictly up, stopping at shoulder height.',
    sets: '3',
    reps: '12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=KPRGmnJcTBc',
  },

  // --- TABLE 5: Knee and Ankle Stabilization (Landing Mechanics) ---
  single_leg_rdl: {
    id: 'single_leg_rdl',
    name: 'Single-Leg RDL',
    category: 'knee_ankle_stability',
    equipment: 'dumbbell',
    muscles: ['Hamstrings', 'Glutes', 'Ankle Stabilizers'],
    purpose: 'Develops immense hamstring eccentric strength required for rapid deceleration and challenges dynamic ankle proprioception.',
    execution: 'Stand on one leg. Hinge at the hips, extending the free leg straight back to counterbalance. Maintain a flat back. Squeeze glutes to return to standing.',
    sets: '3',
    reps: '8-10/leg',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=XCj0o55jPG8',
  },
  single_leg_wall_sit: {
    id: 'single_leg_wall_sit',
    name: 'Single-Leg Wall Sit',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Patellar Tendon'],
    purpose: 'Isometric loading of the patellar tendon; clinically proven to be highly effective for managing and preventing jumpers knee pain.',
    execution: 'Sit against a wall with hips and knees both at 90-degree angles. Extend one leg straight out in front. Hold the isometric position.',
    sets: '3',
    reps: '20-30s/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=V5HFnDrNMH8',
  },
  glute_bridges: {
    id: 'glute_bridges',
    name: 'Glute Bridges',
    category: 'knee_ankle_stability',
    equipment: 'dumbbells',
    muscles: ['Gluteus Maximus'],
    purpose: 'Isolates gluteal activation, ensuring the hips are neurologically primed to bear the brunt of landing forces rather than the fragile knee joints.',
    execution: 'Lie supine with knees bent and feet flat. Place a dumbbell on the pelvis if desired. Drive through the heels to push hips aggressively toward the ceiling.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=Vvn1gXMLbBE',
  },
  broad_jump_stabilize: {
    id: 'broad_jump_stabilize',
    name: 'Broad Jump to Stabilize',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Hamstrings'],
    purpose: 'Teaches force absorption and reinforces correct triple-flexion landing mechanics to prevent valgus collapse.',
    execution: 'Jump forward horizontally. Land softly, dropping the hips back. Freeze the landing position for 2 full seconds, ensuring the knees do not cave inward.',
    sets: '3',
    reps: '5',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=8opxQHJBXOM',
  },
  ankle_sup_pro: {
    id: 'ankle_sup_pro',
    name: 'Ankle Supination and Pronation',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Peroneals', 'Tibialis Posterior'],
    purpose: 'Strengthens the lateral and medial ankle ligaments, drastically increasing resilience against inversion and eversion sprains.',
    execution: 'Stand barefoot. Slowly roll outward onto the outside edges of the feet (supination), then roll inward to the inside edges of the feet (pronation).',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=Y_IzfnlEE5s',
  },
  
  // --- TABLE 6: Specific Rehab Protocols ---
  spanish_squats: {
    id: 'spanish_squats',
    name: 'Spanish Squat Isometric Holds',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight', // requires heavy band
    muscles: ['Patellar Tendon', 'Quadriceps'],
    purpose: 'Clinically proven heavy isometric loading for Jumper\'s Knee (Patellar Tendinopathy) to reduce pain and increase tendon load capacity.',
    execution: 'Loop a heavy resistance band around a solid anchor and behind both knees. Sit back into a squat, keeping the shins completely vertical, resisting the band pulling you forward. Hold.',
    sets: '5',
    reps: '45s Hold',
    impact: 'low',
    unilateral: false,
    trackable: false, // track time
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=kYIIfyRkQh4'
  },
  decline_eccentric_squat: {
    id: 'decline_eccentric_squat',
    name: 'Decline Eccentric Squats',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight', // requires decline board
    muscles: ['Patellar Tendon', 'Quadriceps'],
    purpose: 'Gold standard eccentric protocol for Jumper\'s Knee, forcing the patellar tendon to securely decelerate load.',
    execution: 'Stand on a 25-degree decline board. Perform a slow, 4-second eccentric squat on the injured leg. Push back up using two legs.',
    sets: '3',
    reps: '15/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=fA4h2k_bW8E'
  },
  wall_slides: {
    id: 'wall_slides',
    name: 'Scapular Wall Slides',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Lower Trapezius', 'Serratus Anterior'],
    purpose: 'Restores proper upward rotation of the scapula, critical for attackers suffering from shoulder impingement during the spike phase.',
    execution: 'Stand with your back, head, and elbows flat against a wall. Slow slide your arms upward into a "Y" position without letting your elbows or lower back leave the wall.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=r0wIeeR19mY'
  },
  band_external_rotation: {
    id: 'band_external_rotation',
    name: 'Banded External Rotation',
    category: 'shoulder_prehab',
    equipment: 'bodyweight', // requires band
    muscles: ['Infraspinatus', 'Teres Minor'],
    purpose: 'Isolates the external rotators for shoulder joint stability and pain reduction.',
    execution: 'Anchor a light resistance band at elbow height. Keep your elbow pinned to your side and rotate your forearm outward against the band\'s resistance.',
    sets: '3',
    reps: '15-20',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg',
  },

  // --- NEW: LOWER EXTREMITY EXPLOSIVE POWER ---
  barbell_back_squat: {
    id: 'barbell_back_squat',
    name: 'Barbell Back Squat',
    category: 'vertical_jump',
    equipment: 'dumbbells', 
    muscles: ['Quadriceps', 'Gluteus Maximus', 'Erector Spinae'],
    purpose: 'Builds foundational structural strength required for maximal force production and vertical displacement.',
    execution: 'Stand with feet slightly wider than shoulder-width. Lower hips backward as if sitting into a chair, maintaining a neutral, braced spine. Explode upward concentrically.',
    sets: '3-4',
    reps: '8-12',
    impact: 'medium',
    unilateral: false,
    trackable: true,
    visual: 'SquatSvg',
  },
  split_squat_jumps: {
    id: 'split_squat_jumps',
    name: 'Split Squat Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Glutes', 'Calves'],
    purpose: 'Demands high unilateral stabilization upon landing, mimicking off-balance court recoveries.',
    execution: 'Start in a lunge position, explode upward, and alternate legs in mid-air. Land softly and repeat without rest.',
    sets: '4',
    reps: '30s ON',
    impact: 'high',
    unilateral: true,
    trackable: false,
    visual: 'JumpSvg',
  },
  seated_box_jumps: {
    id: 'seated_box_jumps',
    name: 'Seated Box Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Glutes', 'Quadriceps'],
    purpose: 'Develops pure, starting vertical power from a static position, eliminating all downward momentum and elastic energy.',
    execution: 'Sit on a box. Explode upward onto a higher box in front of you. Step down carefully.',
    sets: '3-4',
    reps: '5',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
  },
  broad_jumps: {
    id: 'broad_jumps',
    name: 'Broad Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Glutes', 'Hamstrings', 'Quadriceps'],
    purpose: 'Develops horizontal force application, mechanically critical for converting the forward momentum of the spike approach into vertical lift.',
    execution: 'Perform consecutive maximal forward bounds. Focus on explosive hip extension and a stable landing.',
    sets: '4',
    reps: '3',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
  },
  jump_rope_intervals: {
    id: 'jump_rope_intervals',
    name: 'Jump Rope Intervals',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Calves', 'Achilles Tendon'],
    purpose: 'Builds fast-twitch muscle fiber endurance and reinforces the ankle stiffness required to transfer force during larger jumps.',
    execution: 'Low-amplitude, repetitive bounding. Maintain a stiff ankle and rebound quickly off the balls of the feet.',
    sets: '3-5',
    reps: '30s ON',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
  },
  
  // --- NEW: COURT SPEED, AGILITY & REACTION ---
  lateral_scissor_steps: {
    id: 'lateral_scissor_steps',
    name: 'Lateral Scissor Steps',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Calves', 'Hip Abductors'],
    purpose: 'Enhances foot speed, lateral neuromuscular quickness, and lower-leg stiffness.',
    execution: 'Face laterally (e.g., to an agility ladder). Scissor-step each foot in and out rapidly while moving laterally. Stay on the balls of the feet.',
    sets: '3',
    reps: '2 lengths',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
  },
  court_speed_drill: {
    id: 'court_speed_drill',
    name: 'Court Speed Drill (5-Cone)',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Total Lower Body'],
    purpose: 'Develops sport-specific spatial awareness and enforces optimal net-facing defensive mechanics.',
    execution: 'Sprint, shuffle, or backpedal from the center to each corner in a randomized pattern, always keeping the torso squared to the net.',
    sets: '4',
    reps: '30s',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
  },
  visual_command_chopping: {
    id: 'visual_command_chopping',
    name: 'Visual Command Chopping',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Nervous System', 'Calves'],
    purpose: 'Exclusively targets alactic energy system and maximizes cognitive processing speed without metabolic fatigue.',
    execution: 'Chop feet rapidly in place. React to visual signals (arms up = sprint forward, arms down = backpedal). Drill strictly lasts 8-10 seconds.',
    sets: '5',
    reps: '8-10s',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
  },
  partner_drop_drill: {
    id: 'partner_drop_drill',
    name: 'Partner Drop Drill',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Nervous System', 'Quadriceps'],
    purpose: 'Compresses the reaction window and forces faster neural firing for defensive digging.',
    execution: 'Assume a low defensive posture. Partner drops a ball unpredictably. Drop center of gravity rapidly to catch it before it bounces twice.',
    sets: '4',
    reps: '6 drops',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'SquatSvg',
  },
  wall_dig_reaction: {
    id: 'wall_dig_reaction',
    name: 'Wall Dig Reaction',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Nervous System', 'Total Body'],
    purpose: 'Challenges visual tracking of an unpredictable rebound trajectory for defensive passing.',
    execution: 'Partner spikes a ball against a wall from behind you. Visually track the rebound and execute a technically sound dig.',
    sets: '3',
    reps: '10 digs',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'SquatSvg',
  },
  lateral_pattern_hops: {
    id: 'lateral_pattern_hops',
    name: 'Lateral & Pattern Hops',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Ankles', 'Hip Abductors'],
    purpose: 'Builds multi-planar ankle stiffness and lateral explosive capacity.',
    execution: 'Hop side-to-side, front-to-back, and corner-to-corner as quickly and stiffly as possible.',
    sets: '3',
    reps: '40 reps',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
  },

  // --- NEW: UPPER EXTREMITY POWER & ATTACKING MECHANICS ---
  med_ball_rotational_throws: {
    id: 'med_ball_rotational_throws',
    name: 'Med Ball Rotational Throws',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Obliques', 'Core', 'Lats'],
    purpose: 'Explicitly overloads the rotational mechanics and transverse plane power required for a spike.',
    execution: 'Stand perpendicular to a solid wall. Rotate explosively through the hips and torso to slam/throw the medicine ball against the wall.',
    sets: '4',
    reps: '6/side',
    impact: 'medium',
    unilateral: true,
    trackable: false,
    visual: 'CoreSvg',
  },
  half_kneeling_landmine_press: {
    id: 'half_kneeling_landmine_press',
    name: 'Half-Kneeling Landmine Press',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Deltoids', 'Pectorals', 'Core'],
    purpose: 'Develops unilateral overhead pressing power while demanding high core stabilization to prevent lateral torso shift.',
    execution: 'Kneel on one leg. Press the barbell or heavy dumbbell upward and forward from the shoulder. Control the descent.',
    sets: '3',
    reps: '8-10/side',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg',
  },
  dumbbell_pullovers: {
    id: 'dumbbell_pullovers',
    name: 'Dumbbell Pullovers',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Latissimus Dorsi', 'Pectorals'],
    purpose: 'Builds the latissimus dorsi, the primary accelerator muscle of the downward arm swing.',
    execution: 'Lie strictly perpendicular across a bench. Lower a dumbbell behind the head with slightly bent elbows, then aggressively pull it back over the chest.',
    sets: '3',
    reps: '10',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'ShoulderSvg',
  },
  cable_thoracic_rotational_row: {
    id: 'cable_thoracic_rotational_row',
    name: 'Thoracic Rotational Row',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Rhomboids', 'Lats', 'Thoracic Spine'],
    purpose: 'Strengthens the posterior chain pulling mechanics vital for rapid arm retraction and cocking.',
    execution: 'Pull a resistance band or cable across the body while actively rotating the thoracic spine. Squeeze the shoulder blade.',
    sets: '3',
    reps: '8-10/side',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg',
  },

  // --- NEW: CORE STABILITY MECHANICS ---
  strict_planks: {
    id: 'strict_planks',
    name: 'Strict Planks',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Core', 'Glutes'],
    purpose: 'Anti-extension mechanism. Squeezing the glutes creates a posterior pelvic tilt, locking the spine into an optimal, injury-resistant neutral position.',
    execution: 'Support body on forearms and toes. Squeeze glutes forcefully and brace abdominals. Hold without sagging.',
    sets: '3',
    reps: '30-60s',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'CoreSvg',
  },
  stability_ball_stir_the_pot: {
    id: 'stability_ball_stir_the_pot',
    name: 'Stir the Pot (Dynamic Plank)',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Core Stabilizers'],
    purpose: 'Dynamic anti-extension. Resists the urge for the hips to sway laterally or drop toward the floor during arm movement.',
    execution: 'Place forearms on a stability ball (or slide pads) in a plank position. Make small, controlled circles with the elbows, keeping the core absolutely rigid.',
    sets: '3',
    reps: '6-10 rots',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'CoreSvg',
  },
  russian_twists: {
    id: 'russian_twists',
    name: 'Russian Twists',
    category: 'attacking_mechanics',
    equipment: 'bodyweight', 
    muscles: ['Obliques'],
    purpose: 'Conditions the internal and external obliques for the repetitive rotational stress of spiking.',
    execution: 'Sit balanced on the sit-bones, leaning slightly back with a braced core. Rotate the torso side to side.',
    sets: '3',
    reps: '20',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'CoreSvg',
  },
  bird_dogs: {
    id: 'bird_dogs',
    name: 'Bird Dogs',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Erector Spinae', 'Glutes'],
    purpose: 'Builds deep spinal stabilizer strength through anti-rotation and posterior chain activation.',
    execution: 'From a quadruped position, simultaneously extend the opposite arm and leg perfectly parallel to the floor. Do not allow hips to tilt or rotate.',
    sets: '3',
    reps: '10/side',
    impact: 'low',
    unilateral: true,
    trackable: false,
    visual: 'CoreSvg',
  },

  // --- NEW: SHOULDER PREHAB & REHAB ---
  serratus_wall_slides: {
    id: 'serratus_wall_slides',
    name: 'Serratus Wall Slides',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Serratus Anterior'],
    purpose: 'Mandatory activation of the serratus anterior to ensure upward rotation of the scapula and prevent subacromial impingement.',
    execution: 'Stand facing a wall with forearms resting against it. Press forearms firmly into wall to protract shoulder blades. Slide upward along the wall.',
    sets: '3',
    reps: '12-15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'ShoulderSvg',
  },
  floor_angels: {
    id: 'floor_angels',
    name: 'Floor Angels',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Lower Trapezius', 'Serratus Anterior'],
    purpose: 'Neurologically deactivates overactive anterior muscles via reciprocal inhibition, allowing pure isolation of scapular stabilizers.',
    execution: 'Lie supine with arms in a 90-degree "L" position on the floor. Slide arms overhead into a press while keeping forearms in constant contact with the floor.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'ShoulderSvg',
  },
  diagonal_shoulder_walks: {
    id: 'diagonal_shoulder_walks',
    name: 'Diagonal Shoulder Walks',
    category: 'shoulder_prehab',
    equipment: 'dumbbells',
    muscles: ['Serratus Anterior', 'Anterior Deltoid'],
    purpose: 'Strengthens the serratus in functional synergy alongside the anterior deltoids and rotator cuff.',
    execution: 'Stand upright with light dumbbells held diagonally at sides. Keeping core tight, slowly lift dumbbells to shoulder height without momentum.',
    sets: '3',
    reps: '10-12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'ShoulderSvg',
  },
  pendulum_swings: {
    id: 'pendulum_swings',
    name: 'Pendulum Swings',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Shoulder Joint'],
    purpose: 'Phase 1 Rehab: Maintains glenohumeral joint space and promotes healing blood flow without muscular contraction.',
    execution: 'Bend over and let the injured arm hang limp. Use gentle torso movement to create small circular swinging motions.',
    sets: '3',
    reps: '30s',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['shoulder'],
    visual: 'ShoulderSvg',
  },
  cane_assisted_rom: {
    id: 'cane_assisted_rom',
    name: 'Cane-Assisted ROM',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Shoulder Joint'],
    purpose: 'Phase 1 Rehab: Passively restores lost range of motion safely.',
    execution: 'Lying supine, hold a light cane with both hands. Use the uninjured arm to passively push and guide the injured arm into overhead flexion.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    safeFor: ['shoulder'],
    visual: 'ShoulderSvg',
  },
  band_internal_rotation: {
    id: 'band_internal_rotation',
    name: 'Band Internal Rotation',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Subscapularis'],
    purpose: 'Isolates and strengthens the internal rotators for balanced joint stability.',
    execution: 'Anchor a band at elbow height. Pin elbow to side and pull the band inward toward the stomach, keeping a locked wrist.',
    sets: '3',
    reps: '12-15',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg',
  },
  shoulder_decelerators: {
    id: 'shoulder_decelerators',
    name: 'Shoulder Decelerators (Eccentric)',
    category: 'shoulder_prehab',
    equipment: 'dumbbells',
    muscles: ['Infraspinatus', 'Teres Minor'],
    purpose: 'Deliberately trains structural tissues to absorb the massive decelerative forces experienced post-spike.',
    execution: 'Lie on your side. Use a heavier dumbbell and slowly lower it into external rotation using an agonizing 5-6 second eccentric count.',
    sets: '3',
    reps: '8-10',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg',
  },
  side_plank_external_rotation: {
    id: 'side_plank_external_rotation',
    name: 'Side Plank w/ External Rotation',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Core', 'Rotator Cuff'],
    purpose: 'Phase 3 Rehab: Taxes the core and forces the rotator cuff to stabilize under intense systemic tension, mimicking aerial attacks.',
    execution: 'Assume a full side plank. Hold a light weight or band in the top hand, pin elbow to ribs, and perform active external rotation.',
    sets: '3',
    reps: '10-12/side',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'CoreSvg',
  },

  // --- NEW: KNEE & ANKLE REHAB / PREHAB ---
  ankle_alphabet: {
    id: 'ankle_alphabet',
    name: 'Ankle Alphabet',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Ankle Joint'],
    purpose: 'Phase 1 Ankle Rehab: Maintains vital joint mobility and acts as a muscle pump to clear inflammatory fluid following an inversion sprain.',
    execution: 'Sit with foot elevated. Trace the letters of the alphabet in the air using only the big toe as the focal point.',
    sets: '2',
    reps: 'A-Z',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    visual: 'SquatSvg',
  },
  towel_scrunches: {
    id: 'towel_scrunches',
    name: 'Towel Scrunches',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Intrinsic Foot Muscles'],
    purpose: 'Strengthens the foot arch and intrinsic muscles crucial for proprioception post-sprain.',
    execution: 'Sit barefoot. Use the toes to scrunch a towel across a smooth floor. Add a weight to the far end to increase difficulty.',
    sets: '3',
    reps: '1-2 mins',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    visual: 'SquatSvg',
  },
  seated_calf_stretches: {
    id: 'seated_calf_stretches',
    name: 'Seated Calf Stretches',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Calves', 'Achilles'],
    purpose: 'Ensures plastic deformation of thick calf tissue to restore full dorsiflexion range of motion.',
    execution: 'Sit with a straight knee. Pull a towel around the ball of the foot and hold strict for 15-30 seconds.',
    sets: '3',
    reps: '30s hold',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    visual: 'SquatSvg',
  },
  four_way_band_ankle: {
    id: 'four_way_band_ankle',
    name: '4-Way Banded Ankle Isotonics',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight', 
    muscles: ['Ankle Stabilizers'],
    purpose: 'Phase 2 Ankle Rehab: Builds endurance in the stabilizing musculature.',
    execution: 'Anchor a loop band around the foot. Perform dorsiflexion, plantarflexion, inversion, and eversion against resistance.',
    sets: '3',
    reps: '15/dir',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    visual: 'JumpSvg',
  },
  balance_progression: {
    id: 'balance_progression',
    name: 'Balance Progression (Proprioception)',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Proprioceptors', 'Ankle Stabilizers'],
    purpose: 'Phase 3 Ankle Rehab: Retrains damaged mechanoreceptors to communicate joint position to the brain, preventing future sprains.',
    execution: 'Static single-leg balance. Progress by closing eyes, then moving to an unstable surface (BOSU/pad) while mimicking volleyball swings.',
    sets: '3',
    reps: '60s/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    visual: 'JumpSvg',
  },
  single_leg_knee_extension_isometrics: {
    id: 'single_leg_knee_extension_isometrics',
    name: 'Single-Leg Knee Extension Isometrics',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight', 
    muscles: ['Quadriceps', 'Patellar Tendon'],
    purpose: 'Stage 1 Patellar Tendinopathy: Heavy isometrics create a profound analgesic effect and decrease motor cortex inhibition.',
    execution: 'Pull a heavy anchored band from a seated position, keeping the knee locked strictly between 30 and 60 degrees of flexion. Hold maximally.',
    sets: '5',
    reps: '45s hold',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    visual: 'SquatSvg',
  }
};

export const EXERCISE_CATEGORIES = {
  vertical_jump: { label: 'Vertical Jump Power', color: 'text-orange-500', bg: 'bg-orange-500/10', border: 'border-orange-500' },
  attacking_mechanics: { label: 'Attacking Power', color: 'text-red-500', bg: 'bg-red-500/10', border: 'border-red-500' },
  lateral_agility: { label: 'Lateral Agility', color: 'text-yellow-500', bg: 'bg-yellow-500/10', border: 'border-yellow-500' },
  shoulder_prehab: { label: 'Shoulder Prehab', color: 'text-teal-500', bg: 'bg-teal-500/10', border: 'border-teal-500' },
  knee_ankle_stability: { label: 'Knee & Ankle Resilience', color: 'text-blue-500', bg: 'bg-blue-500/10', border: 'border-blue-500' },
};
