export const EXERCISES = {
  // --- TABLE 1: Lower Body Strength and Explosiveness (Vertical Jump Focus) ---
  goblet_squat: {
    id: 'goblet_squat',
    name: 'Dumbbell Goblet Squat',
    category: 'vertical_jump',
    equipment: 'dumbbell',
    muscles: ['Quadriceps', 'Gluteus Maximus', 'Core Stabilizers'],
    purpose: 'Develops foundational bilateral lower body strength, improves hip mobility, and ingrains proper squat mechanics necessary for jumping.',
    execution: 'Hold one dumbbell vertically against the chest. Descend until thighs are parallel to the floor. Drive explosively through heels to ascend.',
    sets: '3-4',
    reps: '8-12',
    impact: 'medium',
    unilateral: false,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=lRYBbchqxtI',
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=MeIiIdhvXT4',
  },
  bulgarian_split_squat: {
    id: 'bulgarian_split_squat',
    name: 'Dumbbell Bulgarian Split Squat',
    category: 'vertical_jump',
    equipment: 'dumbbells',
    muscles: ['Quadriceps', 'Gluteus Medius', 'Hamstrings'],
    purpose: 'Corrects unilateral strength imbalances between limbs; places a heavy emphasis on single-leg stabilization and proprioception.',
    execution: 'Elevate the rear foot on a chair or box. Hold dumbbells at sides. Lower hips until the front thigh is parallel to the ground.',
    sets: '3',
    reps: '6-10/leg',
    impact: 'low', // Great for knee issues compared to bilateral heaviness
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=or1frhkjBDc',
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
  },
  rdl: {
    id: 'rdl',
    name: 'Dumbbell Romanian Deadlift (RDL)',
    category: 'vertical_jump',
    equipment: 'dumbbells',
    muscles: ['Hamstrings', 'Gluteus Maximus', 'Erector Spinae'],
    purpose: 'Strengthens the posterior chain for aggressive hip extension power during the jump and eccentric deceleration during landing.',
    execution: 'Hinge at the hips with soft knees, lowering dumbbells down the shins. Squeeze glutes aggressively to return to a standing position.',
    sets: '3',
    reps: '8-12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=CBOhr6H7BEY',
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
  },
  dumbbell_squat_jump: {
    id: 'dumbbell_squat_jump',
    name: 'Dumbbell Squat Jumps',
    category: 'vertical_jump',
    equipment: 'dumbbells', // Light
    muscles: ['Fast-Twitch Quadriceps', 'Calves'],
    purpose: 'Bridges maximum strength and explosive power; enhances the rate of force development (RFD) under mild resistance.',
    execution: 'Hold light dumbbells at sides. Perform a rapid quarter squat and explode vertically. Land softly, absorb the force, and immediately reset.',
    sets: '3',
    reps: '5',
    impact: 'high',
    unilateral: false,
    trackable: true, // Based on dumbbell weight used
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=A-cFYWvaHr0',
  },
  approach_box_jump: {
    id: 'approach_box_jump',
    name: 'Approach Box Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight', // plus sturdy box
    muscles: ['Total Lower Body Kinetic Chain'],
    purpose: 'The most highly sport-specific jump training available. Replicates exact approach mechanics and arm swing timing.',
    execution: 'Perform a traditional 3-step volleyball approach (Left-Right-Left for right-handed hitters) and jump onto a 12-20" box. Step down carefully to reset.',
    sets: '4',
    reps: '4-6',
    impact: 'medium', // Eccentric landing force is removed because of the box
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=HJZh-12p6vg',
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=52FZ-8tjAis',
  },
  tuck_jumps: {
    id: 'tuck_jumps',
    name: 'Tuck Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Hip Flexors', 'Core', 'Quadriceps'],
    purpose: 'Enhances reactive stretch-shortening cycle power and trains rapid hip flexion, essential for hang time.',
    execution: 'Jump vertically, rapidly driving the knees toward the chest. Land softly and immediately bound into the next repetition with minimal ground contact.',
    sets: '3',
    reps: '8',
    impact: 'high',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=r7oBejx1PHM',
    visual: 'JumpSvg'
  },
  single_leg_calf_raise: {
    id: 'single_leg_calf_raise',
    name: 'Single-Leg Calf Raises',
    category: 'vertical_jump',
    equipment: 'dumbbell',
    muscles: ['Gastrocnemius', 'Soleus'],
    purpose: 'Increases ankle plantarflexion power for the critical final push-off phase of the vertical leap.',
    execution: 'Hold one dumbbell, stand on one leg on an elevated edge. Drop the heel below parallel, then press maximally up onto the toes.',
    sets: '3',
    reps: '15-20/leg',
    impact: 'low',
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=Bfl5du8ehao',
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=_XdMSO_qI38',
  },

  // --- TABLE 2: Upper Body Power and Core Stability (Attacking Mechanics) ---
  dumbbell_shoulder_press: {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Anterior and Medial Deltoid', 'Triceps'],
    purpose: 'Builds foundational overhead pressing strength and shoulder stability, directly correlating to spiking power and blocking rigidity.',
    execution: 'Sit or stand with an engaged core. Press dumbbells from shoulder level to full lockout overhead. Control the eccentric lowering phase.',
    sets: '3',
    reps: '6-10',
    impact: 'low',
    unilateral: false,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=E9ShwbwZ1zw',
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
  },
  explosive_pushups: {
    id: 'explosive_pushups',
    name: 'Explosive Push-Ups',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Pectoralis Major', 'Anterior Deltoid'],
    purpose: 'Develops fast-twitch muscle fibers in the chest and anterior shoulder for high-velocity arm swings.',
    execution: 'Lower the chest to the floor, then press up with maximum explosive force, attempting to lift the hands completely off the floor.',
    sets: '3',
    reps: 'Max',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=xiSBrm-Rgms',
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=WbCVlWuHR0A',
  },
  bent_over_rows: {
    id: 'bent_over_rows',
    name: 'Bent-Over Dumbbell Rows',
    category: 'attacking_mechanics', // also acts as prehab
    equipment: 'dumbbells',
    muscles: ['Latissimus Dorsi', 'Rhomboids', 'Biceps'],
    purpose: 'Provides critical antagonistic balance to spiking; decelerates the arm swing safely and stabilizes the scapula.',
    execution: 'Hinge forward, maintaining a flat, neutral spine. Pull dumbbells to the hip crease, squeezing the shoulder blades tightly together.',
    sets: '3',
    reps: '10-12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=IOOLhrkN_NI',
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=roCP6wCXPqo',
  },
  dead_bug: {
    id: 'dead_bug',
    name: 'Dead Bug',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Transverse Abdominis', 'Core Stabilizers'],
    purpose: 'Enhances anti-extension core stability, preventing dangerous lower back hyperextension during the arching phase of a spike.',
    execution: 'Lie supine with arms and legs elevated. Slowly lower the opposite arm and leg to the floor without allowing the lower back to arch off the ground.',
    sets: '2',
    reps: '12/side',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=DqLL45uk2Tk',
    visual: 'CoreSvg',
    videoUrl: 'https://www.youtube.com/watch?v=4XLEnwUr1d8',
  },
  forearm_plank: {
    id: 'forearm_plank',
    name: 'Forearm Plank',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Total Core', 'Rectus Abdominis'],
    purpose: 'Builds isometric core endurance, allowing for improved kinetic transfer from the lower body to the hitting arm.',
    execution: 'Support the body on forearms and toes, maintaining a rigid, straight line from the head to the heels. Breathe steadily.',
    sets: '3',
    reps: '45-60s',
    impact: 'low',
    unilateral: false,
    trackable: false, // Or track time
    videoUrl: 'https://www.youtube.com/watch?v=v25dawSzRTM',
    visual: 'CoreSvg',
    videoUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
  },

  // --- TABLE 3: Multidirectional Agility and Court Speed ---
  skater_jumps: {
    id: 'skater_jumps',
    name: 'Skater Jumps',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Gluteus Medius', 'Adductors', 'Ankles'],
    purpose: 'Elite drill for lateral force production, hip stability, and single-leg deceleration strength.',
    execution: 'Bound laterally from the right leg to the left leg, absorbing the landing deeply into a partial squat. Pause to stabilize, then bound back.',
    sets: '3',
    reps: '8/side',
    impact: 'medium',
    unilateral: true,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=qM5jviFhw9U',
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=xPt5eMJoikk',
  },
  lateral_hurdle_hops: {
    id: 'lateral_hurdle_hops',
    name: 'Lateral Hurdle Hops',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Calves', 'Quadriceps', 'Ankles'],
    purpose: 'Trains extremely rapid ground contact times and lateral change of direction speed.',
    execution: 'Set up a line of small obstacles. Keep feet together and bounce laterally over the obstacles as quickly as possible without losing balance.',
    sets: '3',
    reps: '30s',
    impact: 'high',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=nFnfKRSe0pY',
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=Ue3Kh3LKWQM',
  },
  t_cone_drill: {
    id: 't_cone_drill',
    name: 'T-Cone Agility Drill',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Total Lower Body'],
    purpose: 'Practices the rapid transitions between sprinting, defensive shuffling, and backpedaling.',
    execution: 'Sprint forward 10m to the center cone, shuffle left 5m, shuffle right 10m, shuffle left 5m back to center, then backpedal to the start.',
    sets: '4-6',
    reps: '1',
    impact: 'high',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=_6VZbOneDMY',
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=6Yr2IQXUGGU',
  },
  block_jump_shuffle: {
    id: 'block_jump_shuffle',
    name: 'Block Jump to Lateral Shuffle',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Calves', 'Hip Abductors'],
    purpose: 'Perfectly mimics a middle blockers movement requirements along the net during a rally.',
    execution: 'Perform a maximum vertical block jump. Upon landing, immediately execute two rapid lateral shuffles to the right, then jump again. Repeat to the left.',
    sets: '4',
    reps: '6 jumps',
    impact: 'high',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=ZVf5Xf-2ljk',
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=WxRIFVAGh-o',
  },

  // --- TABLE 4: Shoulder Prehabilitation and Scapular Control ---
  side_lying_external_rotation: {
    id: 'side_lying_external_rotation',
    name: 'Side-Lying External Rotation',
    category: 'shoulder_prehab',
    equipment: 'dumbbell',
    muscles: ['Infraspinatus', 'Teres Minor'],
    purpose: 'Isolates and strengthens the external rotators to counter spiking imbalances and prevent impingement syndrome.',
    execution: 'Lie on side. Pin the working elbow to the ribs at a 90-degree angle. Rotate the dumbbell upward toward the ceiling in a controlled arc.',
    sets: '3',
    reps: '10-15',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=s9TBeBHmPf8',
  },
  side_lying_flexion: {
    id: 'side_lying_flexion',
    name: 'Side-Lying Flexion',
    category: 'shoulder_prehab',
    equipment: 'dumbbell',
    muscles: ['Anterior Deltoid', 'Rotator Cuff'],
    purpose: 'Strengthens the rotator cuff through a safe, planar arc of motion, building endurance in the stabilizers.',
    execution: 'Lie on side. Keep the arm entirely straight and raise the dumbbell in an arc in front of the body, ensuring the weight stays above the torso plane.',
    sets: '3',
    reps: '10-15',
    impact: 'low',
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=4pdh1rdxicQ',
    visual: 'ShoulderSvg'
  },
  prone_ytw: {
    id: 'prone_ytw',
    name: 'Prone Y-T-W Raises',
    category: 'shoulder_prehab',
    equipment: 'bodyweight', // or extremely light
    muscles: ['Lower and Mid Trapezius', 'Rhomboids'],
    purpose: 'Establishes crucial scapular retraction and depression, correcting the forward shoulder posture typical of attackers.',
    execution: 'Lie face down. Raise straight arms to form a "Y" shape, squeezing the blades together. Repeat for "T" and "W" arm positions.',
    sets: '3',
    reps: '10 each',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=tlcuHSz1TQE',
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=AEd5OglxwPw',
  },
  pushup_plus: {
    id: 'pushup_plus',
    name: 'Push-Up Plus',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Serratus Anterior'],
    purpose: 'Prevents scapular winging; an essential movement for ensuring healthy upward rotation of the shoulder blade during overhead extension.',
    execution: 'Ascend to the top of a standard push-up. From there, push the floor away further, actively rounding the upper back to spread the shoulder blades apart.',
    sets: '3',
    reps: '12',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=Jpd24buw2IE',
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=O9ZGIAeHzVE',
  },
  full_can_raise: {
    id: 'full_can_raise',
    name: 'Full Can Raise (Supraspinatus)',
    category: 'shoulder_prehab',
    equipment: 'dumbbells',
    muscles: ['Supraspinatus'],
    purpose: 'Activates the superior rotator cuff muscle responsible for initiating arm abduction and centering the humeral head.',
    execution: 'Stand tall. Raise dumbbells outward at a 45-degree angle (in the scapular plane) with thumbs pointing strictly up, stopping at shoulder height.',
    sets: '3',
    reps: '12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=HgyzwBq436w',
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=KPRGmnJcTBc',
  },

  // --- TABLE 5: Knee and Ankle Stabilization (Landing Mechanics) ---
  single_leg_rdl: {
    id: 'single_leg_rdl',
    name: 'Single-Leg RDL',
    category: 'knee_ankle_stability',
    equipment: 'dumbbell',
    muscles: ['Hamstrings', 'Glutes', 'Ankle Stabilizers'],
    purpose: 'Develops immense hamstring eccentric strength required for rapid deceleration and challenges dynamic ankle proprioception.',
    execution: 'Stand on one leg. Hinge at the hips, extending the free leg straight back to counterbalance. Maintain a flat back. Squeeze glutes to return to standing.',
    sets: '3',
    reps: '8-10/leg',
    impact: 'low',
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=v5JFb2AsSVs',
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=XCj0o55jPG8',
  },
  single_leg_wall_sit: {
    id: 'single_leg_wall_sit',
    name: 'Single-Leg Wall Sit',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Patellar Tendon'],
    purpose: 'Isometric loading of the patellar tendon; clinically proven to be highly effective for managing and preventing jumpers knee pain.',
    execution: 'Sit against a wall with hips and knees both at 90-degree angles. Extend one leg straight out in front. Hold the isometric position.',
    sets: '3',
    reps: '20-30s/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=mDdLC-yKudY',
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=V5HFnDrNMH8',
  },
  glute_bridges: {
    id: 'glute_bridges',
    name: 'Glute Bridges',
    category: 'knee_ankle_stability',
    equipment: 'dumbbells',
    muscles: ['Gluteus Maximus'],
    purpose: 'Isolates gluteal activation, ensuring the hips are neurologically primed to bear the brunt of landing forces rather than the fragile knee joints.',
    execution: 'Lie supine with knees bent and feet flat. Place a dumbbell on the pelvis if desired. Drive through the heels to push hips aggressively toward the ceiling.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=X_IGw8U_e38',
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=Vvn1gXMLbBE',
  },
  broad_jump_stabilize: {
    id: 'broad_jump_stabilize',
    name: 'Broad Jump to Stabilize',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Hamstrings'],
    purpose: 'Teaches force absorption and reinforces correct triple-flexion landing mechanics to prevent valgus collapse.',
    execution: 'Jump forward horizontally. Land softly, dropping the hips back. Freeze the landing position for 2 full seconds, ensuring the knees do not cave inward.',
    sets: '3',
    reps: '5',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=gwWyIWrNHpM',
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=8opxQHJBXOM',
  },
  ankle_sup_pro: {
    id: 'ankle_sup_pro',
    name: 'Ankle Supination and Pronation',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Peroneals', 'Tibialis Posterior'],
    purpose: 'Strengthens the lateral and medial ankle ligaments, drastically increasing resilience against inversion and eversion sprains.',
    execution: 'Stand barefoot. Slowly roll outward onto the outside edges of the feet (supination), then roll inward to the inside edges of the feet (pronation).',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=CMliBKhriQY',
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=Y_IzfnlEE5s',
  },
  
  // --- TABLE 6: Specific Rehab Protocols ---
  spanish_squats: {
    id: 'spanish_squats',
    name: 'Spanish Squat Isometric Holds',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight', // requires heavy band
    muscles: ['Patellar Tendon', 'Quadriceps'],
    purpose: 'Clinically proven heavy isometric loading for Jumper\'s Knee (Patellar Tendinopathy) to reduce pain and increase tendon load capacity.',
    execution: 'Loop a heavy resistance band around a solid anchor and behind both knees. Sit back into a squat, keeping the shins completely vertical, resisting the band pulling you forward. Hold.',
    sets: '5',
    reps: '45s Hold',
    impact: 'low',
    unilateral: false,
    trackable: false, // track time
    videoUrl: 'https://www.youtube.com/watch?v=1CJ3hteGxo4',
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=kYIIfyRkQh4'
  },
  decline_eccentric_squat: {
    id: 'decline_eccentric_squat',
    name: 'Decline Eccentric Squats',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight', // requires decline board
    muscles: ['Patellar Tendon', 'Quadriceps'],
    purpose: 'Gold standard eccentric protocol for Jumper\'s Knee, forcing the patellar tendon to securely decelerate load.',
    execution: 'Stand on a 25-degree decline board. Perform a slow, 4-second eccentric squat on the injured leg. Push back up using two legs.',
    sets: '3',
    reps: '15/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=0UTyP00Ua1M',
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=fA4h2k_bW8E'
  },
  wall_slides: {
    id: 'wall_slides',
    name: 'Scapular Wall Slides',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Lower Trapezius', 'Serratus Anterior'],
    purpose: 'Restores proper upward rotation of the scapula, critical for attackers suffering from shoulder impingement during the spike phase.',
    execution: 'Stand with your back, head, and elbows flat against a wall. Slow slide your arms upward into a "Y" position without letting your elbows or lower back leave the wall.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=tWDGEyMWv10',
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=r0wIeeR19mY'
  },
  band_external_rotation: {
    id: 'band_external_rotation',
    name: 'Banded External Rotation',
    category: 'shoulder_prehab',
    equipment: 'bodyweight', // requires band
    muscles: ['Infraspinatus', 'Teres Minor'],
    purpose: 'Isolates the external rotators for shoulder joint stability and pain reduction.',
    execution: 'Anchor a light resistance band at elbow height. Keep your elbow pinned to your side and rotate your forearm outward against the band\'s resistance.',
    sets: '3',
    reps: '15-20',
    impact: 'low',
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=BY7UKjJMx2A',
    visual: 'ShoulderSvg',
  },

  // --- NEW: LOWER EXTREMITY EXPLOSIVE POWER ---
  barbell_back_squat: {
    id: 'barbell_back_squat',
    name: 'Barbell Back Squat',
    category: 'vertical_jump',
    equipment: 'dumbbells', 
    muscles: ['Quadriceps', 'Gluteus Maximus', 'Erector Spinae'],
    purpose: 'Builds foundational structural strength required for maximal force production and vertical displacement.',
    execution: 'Stand with feet slightly wider than shoulder-width. Lower hips backward as if sitting into a chair, maintaining a neutral, braced spine. Explode upward concentrically.',
    sets: '3-4',
    reps: '8-12',
    impact: 'medium',
    unilateral: false,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=my0tLDaWyDU',
    visual: 'SquatSvg',
  },
  split_squat_jumps: {
    id: 'split_squat_jumps',
    name: 'Split Squat Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Glutes', 'Calves'],
    purpose: 'Demands high unilateral stabilization upon landing, mimicking off-balance court recoveries.',
    execution: 'Start in a lunge position, explode upward, and alternate legs in mid-air. Land softly and repeat without rest.',
    sets: '4',
    reps: '30s ON',
    impact: 'high',
    unilateral: true,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=hiLF_pF3EJM',
    visual: 'JumpSvg',
  },
  seated_box_jumps: {
    id: 'seated_box_jumps',
    name: 'Seated Box Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Glutes', 'Quadriceps'],
    purpose: 'Develops pure, starting vertical power from a static position, eliminating all downward momentum and elastic energy.',
    execution: 'Sit on a box. Explode upward onto a higher box in front of you. Step down carefully.',
    sets: '3-4',
    reps: '5',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=Ogats4wEMlU',
    visual: 'JumpSvg',
  },
  broad_jumps: {
    id: 'broad_jumps',
    name: 'Broad Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Glutes', 'Hamstrings', 'Quadriceps'],
    purpose: 'Develops horizontal force application, mechanically critical for converting the forward momentum of the spike approach into vertical lift.',
    execution: 'Perform consecutive maximal forward bounds. Focus on explosive hip extension and a stable landing.',
    sets: '4',
    reps: '3',
    impact: 'high',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=v0yrBWA3eEs',
    visual: 'JumpSvg',
  },
  jump_rope_intervals: {
    id: 'jump_rope_intervals',
    name: 'Jump Rope Intervals',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Calves', 'Achilles Tendon'],
    purpose: 'Builds fast-twitch muscle fiber endurance and reinforces the ankle stiffness required to transfer force during larger jumps.',
    execution: 'Low-amplitude, repetitive bounding. Maintain a stiff ankle and rebound quickly off the balls of the feet.',
    sets: '3-5',
    reps: '30s ON',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=iC7oJ2NYJ9U',
    visual: 'JumpSvg',
  },
  
  // --- NEW: COURT SPEED, AGILITY & REACTION ---
  lateral_scissor_steps: {
    id: 'lateral_scissor_steps',
    name: 'Lateral Scissor Steps',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Calves', 'Hip Abductors'],
    purpose: 'Enhances foot speed, lateral neuromuscular quickness, and lower-leg stiffness.',
    execution: 'Face laterally (e.g., to an agility ladder). Scissor-step each foot in and out rapidly while moving laterally. Stay on the balls of the feet.',
    sets: '3',
    reps: '2 lengths',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=aNncQWr0jmU',
    visual: 'JumpSvg',
  },
  court_speed_drill: {
    id: 'court_speed_drill',
    name: 'Court Speed Drill (5-Cone)',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Total Lower Body'],
    purpose: 'Develops sport-specific spatial awareness and enforces optimal net-facing defensive mechanics.',
    execution: 'Sprint, shuffle, or backpedal from the center to each corner in a randomized pattern, always keeping the torso squared to the net.',
    sets: '4',
    reps: '30s',
    impact: 'high',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=d01bxcf-VhQ',
    visual: 'JumpSvg',
  },
  visual_command_chopping: {
    id: 'visual_command_chopping',
    name: 'Visual Command Chopping',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Nervous System', 'Calves'],
    purpose: 'Exclusively targets alactic energy system and maximizes cognitive processing speed without metabolic fatigue.',
    execution: 'Chop feet rapidly in place. React to visual signals (arms up = sprint forward, arms down = backpedal). Drill strictly lasts 8-10 seconds.',
    sets: '5',
    reps: '8-10s',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=OcmCcvmOlQ0',
    visual: 'JumpSvg',
  },
  partner_drop_drill: {
    id: 'partner_drop_drill',
    name: 'Partner Drop Drill',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Nervous System', 'Quadriceps'],
    purpose: 'Compresses the reaction window and forces faster neural firing for defensive digging.',
    execution: 'Assume a low defensive posture. Partner drops a ball unpredictably. Drop center of gravity rapidly to catch it before it bounces twice.',
    sets: '4',
    reps: '6 drops',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=qt_SebbfqNY',
    visual: 'SquatSvg',
  },
  wall_dig_reaction: {
    id: 'wall_dig_reaction',
    name: 'Wall Dig Reaction',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Nervous System', 'Total Body'],
    purpose: 'Challenges visual tracking of an unpredictable rebound trajectory for defensive passing.',
    execution: 'Partner spikes a ball against a wall from behind you. Visually track the rebound and execute a technically sound dig.',
    sets: '3',
    reps: '10 digs',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=WGM7FjbDJUA',
    visual: 'SquatSvg',
  },
  lateral_pattern_hops: {
    id: 'lateral_pattern_hops',
    name: 'Lateral & Pattern Hops',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Ankles', 'Hip Abductors'],
    purpose: 'Builds multi-planar ankle stiffness and lateral explosive capacity.',
    execution: 'Hop side-to-side, front-to-back, and corner-to-corner as quickly and stiffly as possible.',
    sets: '3',
    reps: '40 reps',
    impact: 'high',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=0yrvhVeC1Xk',
    visual: 'JumpSvg',
  },

  // --- NEW: UPPER EXTREMITY POWER & ATTACKING MECHANICS ---
  med_ball_rotational_throws: {
    id: 'med_ball_rotational_throws',
    name: 'Med Ball Rotational Throws',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Obliques', 'Core', 'Lats'],
    purpose: 'Explicitly overloads the rotational mechanics and transverse plane power required for a spike.',
    execution: 'Stand perpendicular to a solid wall. Rotate explosively through the hips and torso to slam/throw the medicine ball against the wall.',
    sets: '4',
    reps: '6/side',
    impact: 'medium',
    unilateral: true,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=02c2YLgF8iE',
    visual: 'CoreSvg',
  },
  half_kneeling_landmine_press: {
    id: 'half_kneeling_landmine_press',
    name: 'Half-Kneeling Landmine Press',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Deltoids', 'Pectorals', 'Core'],
    purpose: 'Develops unilateral overhead pressing power while demanding high core stabilization to prevent lateral torso shift.',
    execution: 'Kneel on one leg. Press the barbell or heavy dumbbell upward and forward from the shoulder. Control the descent.',
    sets: '3',
    reps: '8-10/side',
    impact: 'low',
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=PY9HorHANhc',
    visual: 'ShoulderSvg',
  },
  dumbbell_pullovers: {
    id: 'dumbbell_pullovers',
    name: 'Dumbbell Pullovers',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Latissimus Dorsi', 'Pectorals'],
    purpose: 'Builds the latissimus dorsi, the primary accelerator muscle of the downward arm swing.',
    execution: 'Lie strictly perpendicular across a bench. Lower a dumbbell behind the head with slightly bent elbows, then aggressively pull it back over the chest.',
    sets: '3',
    reps: '10',
    impact: 'low',
    unilateral: false,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=Datv2L6t3-4',
    visual: 'ShoulderSvg',
  },
  cable_thoracic_rotational_row: {
    id: 'cable_thoracic_rotational_row',
    name: 'Thoracic Rotational Row',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Rhomboids', 'Lats', 'Thoracic Spine'],
    purpose: 'Strengthens the posterior chain pulling mechanics vital for rapid arm retraction and cocking.',
    execution: 'Pull a resistance band or cable across the body while actively rotating the thoracic spine. Squeeze the shoulder blade.',
    sets: '3',
    reps: '8-10/side',
    impact: 'low',
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=l3Ze_9iXL-M',
    visual: 'ShoulderSvg',
  },

  // --- NEW: CORE STABILITY MECHANICS ---
  strict_planks: {
    id: 'strict_planks',
    name: 'Strict Planks',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Core', 'Glutes'],
    purpose: 'Anti-extension mechanism. Squeezing the glutes creates a posterior pelvic tilt, locking the spine into an optimal, injury-resistant neutral position.',
    execution: 'Support body on forearms and toes. Squeeze glutes forcefully and brace abdominals. Hold without sagging.',
    sets: '3',
    reps: '30-60s',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=6LqqeBtFn9M',
    visual: 'CoreSvg',
  },
  stability_ball_stir_the_pot: {
    id: 'stability_ball_stir_the_pot',
    name: 'Stir the Pot (Dynamic Plank)',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Core Stabilizers'],
    purpose: 'Dynamic anti-extension. Resists the urge for the hips to sway laterally or drop toward the floor during arm movement.',
    execution: 'Place forearms on a stability ball (or slide pads) in a plank position. Make small, controlled circles with the elbows, keeping the core absolutely rigid.',
    sets: '3',
    reps: '6-10 rots',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=v25dawSzRTM',
    visual: 'CoreSvg',
  },
  russian_twists: {
    id: 'russian_twists',
    name: 'Russian Twists',
    category: 'attacking_mechanics',
    equipment: 'bodyweight', 
    muscles: ['Obliques'],
    purpose: 'Conditions the internal and external obliques for the repetitive rotational stress of spiking.',
    execution: 'Sit balanced on the sit-bones, leaning slightly back with a braced core. Rotate the torso side to side.',
    sets: '3',
    reps: '20',
    impact: 'low',
    unilateral: false,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=-BzNffL_6YE',
    visual: 'CoreSvg',
  },
  bird_dogs: {
    id: 'bird_dogs',
    name: 'Bird Dogs',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Erector Spinae', 'Glutes'],
    purpose: 'Builds deep spinal stabilizer strength through anti-rotation and posterior chain activation.',
    execution: 'From a quadruped position, simultaneously extend the opposite arm and leg perfectly parallel to the floor. Do not allow hips to tilt or rotate.',
    sets: '3',
    reps: '10/side',
    impact: 'low',
    unilateral: true,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=_1j_HWknGLg',
    visual: 'CoreSvg',
  },

  // --- NEW: SHOULDER PREHAB & REHAB ---
  serratus_wall_slides: {
    id: 'serratus_wall_slides',
    name: 'Serratus Wall Slides',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Serratus Anterior'],
    purpose: 'Mandatory activation of the serratus anterior to ensure upward rotation of the scapula and prevent subacromial impingement.',
    execution: 'Stand facing a wall with forearms resting against it. Press forearms firmly into wall to protract shoulder blades. Slide upward along the wall.',
    sets: '3',
    reps: '12-15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=eI7IHxvhA3k',
    visual: 'ShoulderSvg',
  },
  floor_angels: {
    id: 'floor_angels',
    name: 'Floor Angels',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Lower Trapezius', 'Serratus Anterior'],
    purpose: 'Neurologically deactivates overactive anterior muscles via reciprocal inhibition, allowing pure isolation of scapular stabilizers.',
    execution: 'Lie supine with arms in a 90-degree "L" position on the floor. Slide arms overhead into a press while keeping forearms in constant contact with the floor.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    videoUrl: 'https://www.youtube.com/watch?v=Y8efRb6nXD0',
    visual: 'ShoulderSvg',
  },
  diagonal_shoulder_walks: {
    id: 'diagonal_shoulder_walks',
    name: 'Diagonal Shoulder Walks',
    category: 'shoulder_prehab',
    equipment: 'dumbbells',
    muscles: ['Serratus Anterior', 'Anterior Deltoid'],
    purpose: 'Strengthens the serratus in functional synergy alongside the anterior deltoids and rotator cuff.',
    execution: 'Stand upright with light dumbbells held diagonally at sides. Keeping core tight, slowly lift dumbbells to shoulder height without momentum.',
    sets: '3',
    reps: '10-12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'ShoulderSvg',
  },
  pendulum_swings: {
    id: 'pendulum_swings',
    name: 'Pendulum Swings',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Shoulder Joint'],
    purpose: 'Phase 1 Rehab: Maintains glenohumeral joint space and promotes healing blood flow without muscular contraction.',
    execution: 'Bend over and let the injured arm hang limp. Use gentle torso movement to create small circular swinging motions.',
    sets: '3',
    reps: '30s',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['shoulder'],
    videoUrl: 'https://www.youtube.com/watch?v=Rt_F1xjCUK4',
    visual: 'ShoulderSvg',
  },
  cane_assisted_rom: {
    id: 'cane_assisted_rom',
    name: 'Cane-Assisted ROM',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Shoulder Joint'],
    purpose: 'Phase 1 Rehab: Passively restores lost range of motion safely.',
    execution: 'Lying supine, hold a light cane with both hands. Use the uninjured arm to passively push and guide the injured arm into overhead flexion.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    safeFor: ['shoulder'],
    videoUrl: 'https://www.youtube.com/watch?v=YvfIhAKPC4k',
    visual: 'ShoulderSvg',
  },
  band_internal_rotation: {
    id: 'band_internal_rotation',
    name: 'Band Internal Rotation',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Subscapularis'],
    purpose: 'Isolates and strengthens the internal rotators for balanced joint stability.',
    execution: 'Anchor a band at elbow height. Pin elbow to side and pull the band inward toward the stomach, keeping a locked wrist.',
    sets: '3',
    reps: '12-15',
    impact: 'low',
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=dS9ORQCnWsE',
    visual: 'ShoulderSvg',
  },
  shoulder_decelerators: {
    id: 'shoulder_decelerators',
    name: 'Shoulder Decelerators (Eccentric)',
    category: 'shoulder_prehab',
    equipment: 'dumbbells',
    muscles: ['Infraspinatus', 'Teres Minor'],
    purpose: 'Deliberately trains structural tissues to absorb the massive decelerative forces experienced post-spike.',
    execution: 'Lie on your side. Use a heavier dumbbell and slowly lower it into external rotation using an agonizing 5-6 second eccentric count.',
    sets: '3',
    reps: '8-10',
    impact: 'low',
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=fVbyKGs23_E',
    visual: 'ShoulderSvg',
  },
  side_plank_external_rotation: {
    id: 'side_plank_external_rotation',
    name: 'Side Plank w/ External Rotation',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Core', 'Rotator Cuff'],
    purpose: 'Phase 3 Rehab: Taxes the core and forces the rotator cuff to stabilize under intense systemic tension, mimicking aerial attacks.',
    execution: 'Assume a full side plank. Hold a light weight or band in the top hand, pin elbow to ribs, and perform active external rotation.',
    sets: '3',
    reps: '10-12/side',
    impact: 'low',
    unilateral: true,
    trackable: true,
    videoUrl: 'https://www.youtube.com/watch?v=1F0IfCUr7YY',
    visual: 'CoreSvg',
  },

  // --- NEW: KNEE & ANKLE REHAB / PREHAB ---
  ankle_alphabet: {
    id: 'ankle_alphabet',
    name: 'Ankle Alphabet',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Ankle Joint'],
    purpose: 'Phase 1 Ankle Rehab: Maintains vital joint mobility and acts as a muscle pump to clear inflammatory fluid following an inversion sprain.',
    execution: 'Sit with foot elevated. Trace the letters of the alphabet in the air using only the big toe as the focal point.',
    sets: '2',
    reps: 'A-Z',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    visual: 'SquatSvg',
  },
  towel_scrunches: {
    id: 'towel_scrunches',
    name: 'Towel Scrunches',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Intrinsic Foot Muscles'],
    purpose: 'Strengthens the foot arch and intrinsic muscles crucial for proprioception post-sprain.',
    execution: 'Sit barefoot. Use the toes to scrunch a towel across a smooth floor. Add a weight to the far end to increase difficulty.',
    sets: '3',
    reps: '1-2 mins',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    videoUrl: 'https://www.youtube.com/watch?v=RoEmHev3KZ8',
    visual: 'SquatSvg',
  },
  seated_calf_stretches: {
    id: 'seated_calf_stretches',
    name: 'Seated Calf Stretches',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Calves', 'Achilles'],
    purpose: 'Ensures plastic deformation of thick calf tissue to restore full dorsiflexion range of motion.',
    execution: 'Sit with a straight knee. Pull a towel around the ball of the foot and hold strict for 15-30 seconds.',
    sets: '3',
    reps: '30s hold',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    videoUrl: 'https://www.youtube.com/watch?v=dh5cQlchiA8',
    visual: 'SquatSvg',
  },
  four_way_band_ankle: {
    id: 'four_way_band_ankle',
    name: '4-Way Banded Ankle Isotonics',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight', 
    muscles: ['Ankle Stabilizers'],
    purpose: 'Phase 2 Ankle Rehab: Builds endurance in the stabilizing musculature.',
    execution: 'Anchor a loop band around the foot. Perform dorsiflexion, plantarflexion, inversion, and eversion against resistance.',
    sets: '3',
    reps: '15/dir',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    videoUrl: 'https://www.youtube.com/watch?v=WWVZyqZLOJY',
    visual: 'JumpSvg',
  },
  balance_progression: {
    id: 'balance_progression',
    name: 'Balance Progression (Proprioception)',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Proprioceptors', 'Ankle Stabilizers'],
    purpose: 'Phase 3 Ankle Rehab: Retrains damaged mechanoreceptors to communicate joint position to the brain, preventing future sprains.',
    execution: 'Static single-leg balance. Progress by closing eyes, then moving to an unstable surface (BOSU/pad) while mimicking volleyball swings.',
    sets: '3',
    reps: '60s/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    videoUrl: 'https://www.youtube.com/watch?v=WRfWHHT7IWk',
    visual: 'SquatSvg',
  },
  single_leg_knee_extension_isometrics: {
    id: 'single_leg_knee_extension_isometrics',
    name: 'Single-Leg Knee Extension Isometrics',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight', 
    muscles: ['Quadriceps', 'Patellar Tendon'],
    purpose: 'Stage 1 Patellar Tendinopathy: Heavy isometrics create a profound analgesic effect and decrease motor cortex inhibition.',
    execution: 'Pull a heavy anchored band from a seated position, keeping the knee locked strictly between 30 and 60 degrees of flexion. Hold maximally.',
    sets: '5',
    reps: '45s hold',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee'],
    videoUrl: 'https://www.youtube.com/watch?v=M94AS_Sk8EQ',
    visual: 'SquatSvg',
  },

  // --- KNEE & REVALIDATION PROTOCOL EXERCISES (From Research Report) ---
  clamshell_60_90: {
    id: 'clamshell_60_90',
    name: 'Clamshell at 60-90° Knee Flexion',
    category: 'knee_revalidation',
    equipment: 'bands',
    muscles: ['Gluteus Medius', 'Gluteus Maximus (Posterieur)'],
    purpose: 'Isolates hip abductors & external rotators while minimizing TFL engagement to prevent dynamic knee valgus (DKV).',
    execution: 'Lie on side, hips at 45°, knees at 90°. Rotate upper knee toward ceiling keeping feet together. Hold 2s isometric contraction at peak.',
    sets: '3',
    reps: '15/side',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl', 'patellar_tendon'],
    visual: 'SquatSvg',
    cues: 'Rotate thigh in hip socket without arching lower back or tilting pelvis backward.',
    volleyballContext: 'Builds fundamental neuromuscular control to resist valgus collapse during defensive stance and approach plant.',
  },
  side_lying_hip_abduction: {
    id: 'side_lying_hip_abduction',
    name: 'Side-Lying Hip Abduction',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Gluteus Medius'],
    purpose: 'Delivers maximum MVIC gluteus medius activation in an unloaded open kinetic chain setting for knee rehab.',
    execution: 'Side-lying, raise top leg straight up and slightly back with heel leading. Controlled 3-second eccentric lower.',
    sets: '3',
    reps: '12-15/side',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl', 'patellar_tendon'],
    visual: 'SquatSvg',
    cues: 'Drive heel to ceiling; do not let toes point upward or swing leg forward.',
    volleyballContext: 'Provides pure hip strength needed for lateral shuffle steps without knee compensation.',
  },
  glute_bridge_band: {
    id: 'glute_bridge_band',
    name: 'Glute Bridge with Resistance Band',
    category: 'knee_revalidation',
    equipment: 'bands',
    muscles: ['Gluteus Maximus', 'Gluteus Medius'],
    purpose: 'Trains hip extension with simultaneous isometric abduction against a band to control femoral rotation in closed kinetic chain.',
    execution: 'Lie supine, knees 90°, heavy loop band above knees. Drive hips up through heels while pressing knees outward against band. Hold 2s top.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    safeFor: ['knee', 'acl', 'patellar_tendon'],
    visual: 'SquatSvg',
    cues: 'Drive floor away with heels, tear band apart with knees, keep core braced to protect lower back.',
    volleyballContext: 'Retrains gluteal power for spike jump takeoff instead of relying on lower back hyperextension.',
  },
  vmo_wall_sit_ball: {
    id: 'vmo_wall_sit_ball',
    name: 'VMO Wall Sit with Ball Squeeze',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Vastus Medialis Obliquus (VMO)', 'Adductors'],
    purpose: 'Isolates VMO at 60° knee flexion to optimize VMO/VL activation ratio and eliminate patellar maltracking.',
    execution: 'Slide down wall to 60° knee flexion. Squeeze a volleyball/medicine ball firmly between knees for 30-45s hold.',
    sets: '3',
    reps: '30-45s hold',
    impact: 'low',
    unilateral: false,
    trackable: false,
    safeFor: ['knee', 'acl', 'patellar_tendon'],
    visual: 'SquatSvg',
    cues: 'Crush the ball evenly with both knees and focus on contracting the tear-drop muscle on the inner knee.',
    volleyballContext: 'Analgesic tendon loading protocol for patellar tendinopathy & PFPS (jumper knee revalidation).',
  },
  quadruped_hip_ext_knee_flexed: {
    id: 'quadruped_hip_ext_knee_flexed',
    name: 'Quadruped Hip Extension (Bent Knee)',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Gluteus Maximus'],
    purpose: 'Flexed knee puts hamstrings in active insufficiency, forcing pure gluteus maximus drive.',
    execution: 'On hands and knees, maintain 90° knee angle and drive sole of foot toward ceiling. Pause at top, keep spine neutral.',
    sets: '3',
    reps: '12/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl', 'patellar_tendon'],
    visual: 'SquatSvg',
    cues: 'Stamp a footprint into the ceiling; stop lifting as soon as lower back wants to arch.',
    volleyballContext: 'Improves unilateral glute thrust and pelvic stability in the air prior to spike arm cocking.',
  },
  single_leg_squat_box_tap: {
    id: 'single_leg_squat_box_tap',
    name: 'Single-Leg Squat (Box Tap)',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Gluteus Medius', 'Gluteus Maximus'],
    purpose: 'Controls eccentric gravity on 1 leg with zero valgus caving, building single-leg strength.',
    execution: 'Stand on 1 leg in front of a box. Hinge hips back and descend softly until glute brushes box. Drive back up through midfoot.',
    sets: '3',
    reps: '8-10/leg',
    impact: 'medium',
    unilateral: true,
    trackable: true,
    safeFor: ['knee', 'acl'],
    visual: 'SquatSvg',
    cues: 'Touch the box like thin glass without sitting down; keep kneecap tracking strictly over 2nd toe.',
    volleyballContext: 'Mirrors single-leg landing absorption after blocking or plant step approach.',
  },
  single_leg_rdl: {
    id: 'single_leg_rdl',
    name: 'Single-Leg Romanian Deadlift (SL RDL)',
    category: 'knee_revalidation',
    equipment: 'dumbbells',
    muscles: ['Hamstrings', 'Gluteus Maximus', 'Hip Rotators'],
    purpose: 'Eccentric hamstring loading for tibial deceleration and ACL protection.',
    execution: 'Stand on 1 leg with soft knee. Hinge at hips extending free leg straight back. Keep pelvis level to floor.',
    sets: '3',
    reps: '8-10/leg',
    impact: 'low',
    unilateral: true,
    trackable: true,
    safeFor: ['knee', 'acl', 'patellar_tendon'],
    visual: 'SquatSvg',
    cues: 'Rotate free hip bone and belly button toward floor during descent to prevent hip flare.',
    volleyballContext: 'Deceleration strength for low defensive digs and posterior chain vertical jump engine.',
  },
  lateral_monster_walks: {
    id: 'lateral_monster_walks',
    name: 'Lateral Monster Walks with Band',
    category: 'knee_revalidation',
    equipment: 'bands',
    muscles: ['Gluteus Medius', 'Gluteus Maximus'],
    purpose: 'Closed-chain dynamic lateral activation in semi-squat to build hip abductor stiffness.',
    execution: 'Loop band around forefeet or ankles. Athletic stance (30° knee flex). Step wide lead with heel, trailing foot follows under tension.',
    sets: '3',
    reps: '15 steps/dir',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl', 'patellar_tendon'],
    visual: 'SquatSvg',
    cues: 'Stay low; step from heel as if walking in a low tunnel; do not let trailing knee snap inward.',
    volleyballContext: 'Translates directly to lateral net shuffle steps before block positioning.',
  },
  forward_step_down: {
    id: 'forward_step_down',
    name: 'Forward Step-Down (Eccentric VMO)',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Quadriceps (VMO)', 'Hip Stabilizers'],
    purpose: 'Optimizes patellofemoral tracking through slow closed-chain eccentric VMO deceleration.',
    execution: 'Stand on 20cm box. Flex stance knee slowly, lowering free heel toward floor until it taps lightly. Drive back up.',
    sets: '3',
    reps: '10/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl', 'patellar_tendon'],
    visual: 'SquatSvg',
    cues: 'Land as if stepping on eggshells; descent should be slow and controlled with hips perfectly level.',
    volleyballContext: 'Replicates impulse absorption during last plant steps of spike approach.',
  },
  bosu_single_leg_balance: {
    id: 'bosu_single_leg_balance',
    name: 'Single-Leg Balance on Unstable Surface (BOSU/Pad)',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Ankle Stabilizers', 'Intrinsic Foot', 'Gluteus Medius'],
    purpose: 'Proprioceptive feedback to neutralize DKV on uneven impact or sand.',
    execution: 'Balance on dome of BOSU or Airex pad with soft knee (15° flex). Maintain center of gravity through micro-adjustments.',
    sets: '3',
    reps: '45-60s/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl', 'patellar_tendon'],
    visual: 'JumpSvg',
    cues: 'Claw floor with toes and use glutes like a rudder to keep the ship straight.',
    volleyballContext: 'Prevents ankle rolls & ACL twists on beach volleyball sand or landing on another player foot.',
  },
  y_balance_reaches: {
    id: 'y_balance_reaches',
    name: 'Y-Balance Excursion Reaches (YBT)',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Gluteus Medius', 'Core'],
    purpose: 'Trains dynamic multi-planar stability to eliminate asymmetry in anterior/posterolateral reach.',
    execution: 'Balance on 1 leg at Y-center. Squat on stance leg while free foot reaches Anterior, Posteromedial, Posterolateral touching lightly.',
    sets: '3',
    reps: '3 cycles/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl'],
    visual: 'SquatSvg',
    cues: 'Free foot is light as a feather; all concrete weight stays anchored in your stance heel.',
    volleyballContext: 'Imitates extreme reach required when diving diagonally or laterally for out-of-system balls.',
  },
  perturbation_catch: {
    id: 'perturbation_catch',
    name: 'Perturbation Catch (Dual-Tasking Balance)',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Kinetic Chain Stabilizers', 'Core'],
    purpose: 'Reactive neuromuscular control under cognitive load to automate reflex valgus prevention.',
    execution: 'Stand on 1 leg. Catch unpredictable medicine ball / volleyball passes from partner or wall rebounds without losing knee alignment.',
    sets: '3',
    reps: '12 catches/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl'],
    visual: 'JumpSvg',
    cues: 'Absorb ball with core and hips like shock absorbers without allowing stance knee to wobble.',
    volleyballContext: 'Automates knee stability when visual focus is on the ball trajectory rather than ground.',
  },
  single_leg_hop_stick: {
    id: 'single_leg_hop_stick',
    name: 'Single-Leg Hop and Stick (3s Hold)',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Hamstrings', 'Calves', 'Gluteus'],
    purpose: 'Conditions joint structures for eccentric ground reaction force absorption without valgus collapse.',
    execution: 'Hop forward on 1 leg, land softly on same foot and freeze for 3 solid seconds like a statue.',
    sets: '3',
    reps: '6 sticks/leg',
    impact: 'medium',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl'],
    visual: 'JumpSvg',
    cues: 'Land like a ninja: silent, absorbing through ankle, knee, and hip simultaneously. Hold 3s!',
    volleyballContext: 'Foundation before heavy plyometrics; minimizes peak shock loads that lead to tendon degeneration.',
  },
  cutting_maneuver_45: {
    id: 'cutting_maneuver_45',
    name: '45° Cutting Maneuver & Deceleration',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Gluteus Medius', 'External Rotators', 'ACL/MCL Protection'],
    purpose: 'Trains joint tolerance against high frontal/transverse shear forces during sharp direction changes.',
    execution: 'Sprint forward to cone, plant outside foot with aggressive deceleration, cut 45° to next cone keeping knee aligned over foot.',
    sets: '3',
    reps: '6 cuts/side',
    impact: 'high',
    unilateral: true,
    trackable: false,
    safeFor: ['acl'],
    visual: 'JumpSvg',
    cues: 'Drop shoulders over plant foot; push hard off outside heel and prevent knee from collapsing inward.',
    volleyballContext: 'Crucial for setters and defenders making sudden reactive direction shifts.',
  },
  drop_jump_soft_landing: {
    id: 'drop_jump_soft_landing',
    name: 'Drop Jump with Soft Landing (Anti-Stiffness)',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Patellar Tendon', 'Gluteus'],
    purpose: 'Soft landing mechanics dissipate kinetic energy to prevent patellar tendon micro-trauma.',
    execution: 'Step off 30cm box. Land on both forefeet simultaneously, bending deep at knees & hips like a spring to absorb silent impact.',
    sets: '3',
    reps: '6 landings',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    safeFor: ['knee', 'patellar_tendon'],
    visual: 'JumpSvg',
    cues: 'Touch floor like a cat; absorb into hips and eliminate bone-on-bone thud.',
    volleyballContext: 'Prepares tendon stiffness for repeated landings after thousands of block and spike jumps.',
  },
  lateral_bound_stick: {
    id: 'lateral_bound_stick',
    name: 'Lateral Bound and Stick',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Gluteus Medius', 'Abductors'],
    purpose: 'Trains single-leg lateral landing stability under frontal plane forces.',
    execution: 'Bound sideways explosively from left leg to right leg. Plant right foot and stick landing 2s with zero valgus caving.',
    sets: '3',
    reps: '5 bounds/side',
    impact: 'medium',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl'],
    visual: 'JumpSvg',
    cues: 'Fly wide, land rock-solid; block knee from rolling over inner edge of shoe.',
    volleyballContext: 'Replicates last-minute lateral stepping along net tape to close a block.',
  },
  block_jump_single_leg_landing: {
    id: 'block_jump_single_leg_landing',
    name: 'Block Jump to Single-Leg Landing',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Lower Kinetic Chain', 'Core'],
    purpose: 'Trains single-leg shock absorption under volleyball block jump conditions.',
    execution: 'Perform maximum vertical block jump at net/wall. Shift weight at peak to land softly on single designated leg.',
    sets: '3',
    reps: '4/side',
    impact: 'high',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'acl'],
    visual: 'JumpSvg',
    cues: 'Reach maximum height, convert landing like a cat onto designated foot, bend landing deep.',
    volleyballContext: 'Simulates real match single-leg block landings after net drift or collisions.',
  },
  forward_approach_deceleration: {
    id: 'forward_approach_deceleration',
    name: 'Forward Spike Approach Deceleration',
    category: 'knee_revalidation',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Patellar Tendon', 'Gluteus'],
    purpose: 'Conditions patellar tendon for high horizontal-to-vertical deceleration loads.',
    execution: 'Full speed 3-step spike approach. Instead of jumping, plant feet and freeze momentum instantly in a deep springy squat.',
    sets: '3',
    reps: '5 approach stops',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    safeFor: ['knee', 'patellar_tendon'],
    visual: 'JumpSvg',
    cues: 'Plant foot like a wall and anchor momentum in thighs; stop horizontal motion in hips.',
    volleyballContext: 'Strengthens patellar tendon specifically for spike approach plant step forces.',
  },

  // --- UPPER BODY & CORE REVALIDATION EXERCISES (From Research Report) ---
  blackburns_iytw: {
    id: 'blackburns_iytw',
    name: 'Blackburns (I, Y, T, W)',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Lower Trapezius', 'Rhomboids', 'Infraspinatus'],
    purpose: 'Restores scapular dyskinesia by strengthening lower trapezius and infraspinatus to prevent supraspinatus impingement.',
    execution: 'Lie prone. Raise arms into I, Y, T, W positions with thumbs to ceiling. Hold each 5 seconds.',
    sets: '3',
    reps: '4 holds (I,Y,T,W)',
    impact: 'low',
    unilateral: false,
    trackable: false,
    safeFor: ['shoulder'],
    visual: 'ShoulderSvg',
    cues: 'Squeeze shoulder blades down and back; thumbs pointing to sky.',
    volleyballContext: 'Ensures shoulder girdle safely handles high cocking phase extension in spike swings.',
  },
  wall_slides_protraction: {
    id: 'wall_slides_protraction',
    name: 'Wall Slides with Scapular Protraction',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Serratus Anterior', 'Lower Trap'],
    purpose: 'Activates serratus anterior for upward scapular rotation to clear subacromial space.',
    execution: 'Forearms on wall at 90°. Slide arms upward on wall while actively pushing forearms into wall (protracting scapulae).',
    sets: '3',
    reps: '12',
    impact: 'low',
    unilateral: false,
    trackable: false,
    safeFor: ['shoulder'],
    visual: 'ShoulderSvg',
    cues: 'Hugging the ribcage with serratus anterior as arms slide overhead.',
    volleyballContext: 'Prevents subacromial impingement during block reach and high contact spike hit.',
  },
  side_lying_external_rotation: {
    id: 'side_lying_external_rotation',
    name: 'Side-Lying External Rotation (FDR Focus)',
    category: 'shoulder_prehab',
    equipment: 'dumbbell',
    muscles: ['Infraspinatus', 'Teres Minor', 'Posterior Deltoid'],
    purpose: 'Improves Functional Deceleration Ratio (FDR) to brake high-speed internal rotation (7000°/s) and prevent anterior subluxation.',
    execution: 'Lie on side with towel roll under elbow. Rotate light dumbbell upward from abdomen to ceiling with 3s eccentric lower.',
    sets: '3',
    reps: '12-15/side',
    impact: 'low',
    unilateral: true,
    trackable: true,
    safeFor: ['shoulder'],
    visual: 'ShoulderSvg',
    cues: 'Keep elbow pinned to towel roll; control descent slowly.',
    volleyballContext: 'Brakes the arm safely during follow-through decelerations.',
  },
  banded_pallof_press: {
    id: 'banded_pallof_press',
    name: 'Banded Pallof Press (Anti-Rotation)',
    category: 'shoulder_prehab',
    equipment: 'bands',
    muscles: ['Transversus Abdominis', 'Obliques', 'Multifidus'],
    purpose: 'Rigid anti-rotation core stability to prevent lumbar hyperextension and core energy leak.',
    execution: 'Stand perpendicular to band anchor. Hold handle at chest, press straight out, hold 2s against rotation vector, return to chest.',
    sets: '3',
    reps: '10/side',
    impact: 'low',
    unilateral: true,
    trackable: false,
    safeFor: ['knee', 'shoulder', 'back'],
    visual: 'CoreSvg',
    cues: 'Brace core solid as a rock; do not allow band to rotate your shoulders or hips.',
    volleyballContext: 'Prevents core energy leaks, transferring power cleanly from legs to spike arm.',
  },
  half_kneeling_overhead_press: {
    id: 'half_kneeling_overhead_press',
    name: 'Half-Kneeling Kettlebell Overhead Press',
    category: 'shoulder_prehab',
    equipment: 'dumbbell',
    muscles: ['Deltoids', 'Core', 'Gluteus Medius'],
    purpose: 'Links pelvic-hip stability with true overhead vertical reach under core constraint.',
    execution: 'Half-kneeling stance (back knee down, front knee 90°). Press dumbbell/kettlebell overhead keeping ribcage locked down.',
    sets: '3',
    reps: '8/side',
    impact: 'low',
    unilateral: true,
    trackable: true,
    safeFor: ['knee', 'shoulder'],
    visual: 'ShoulderSvg',
    cues: 'Squeeze down-side glute; press overhead without flaring ribs or arching back.',
    volleyballContext: 'Builds stable overhead reach for high-contact spikes and net blocking.',
  }
};

export const EXERCISE_CATEGORIES = {
  knee_revalidation: { label: 'Knee Revalidation & Strengthening', color: 'text-indigo-500', bg: 'bg-indigo-500/10', border: 'border-indigo-500' },
  vertical_jump: { label: 'Vertical Jump Power', color: 'text-orange-500', bg: 'bg-orange-500/10', border: 'border-orange-500' },
  attacking_mechanics: { label: 'Attacking Power', color: 'text-red-500', bg: 'bg-red-500/10', border: 'border-red-500' },
  lateral_agility: { label: 'Lateral Agility', color: 'text-yellow-500', bg: 'bg-yellow-500/10', border: 'border-yellow-500' },
  shoulder_prehab: { label: 'Shoulder Prehab', color: 'text-teal-500', bg: 'bg-teal-500/10', border: 'border-teal-500' },
  knee_ankle_stability: { label: 'Knee & Ankle Resilience', color: 'text-blue-500', bg: 'bg-blue-500/10', border: 'border-blue-500' },
};
