export const EXERCISES = {
  // --- TABLE 1: Lower Body Strength and Explosiveness (Vertical Jump Focus) ---
  goblet_squat: {
    id: 'goblet_squat',
    name: 'Dumbbell Goblet Squat',
    category: 'vertical_jump',
    equipment: 'dumbbell',
    muscles: ['Quadriceps', 'Gluteus Maximus', 'Core Stabilizers'],
    purpose: 'Develops foundational bilateral lower body strength, improves hip mobility, and ingrains proper squat mechanics necessary for jumping.',
    execution: 'Hold one dumbbell vertically against the chest. Descend until thighs are parallel to the floor. Drive explosively through heels to ascend.',
    sets: '3-4',
    reps: '8-12',
    impact: 'medium',
    unilateral: false,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=MeIiIdhvXT4',
  },
  bulgarian_split_squat: {
    id: 'bulgarian_split_squat',
    name: 'Dumbbell Bulgarian Split Squat',
    category: 'vertical_jump',
    equipment: 'dumbbells',
    muscles: ['Quadriceps', 'Gluteus Medius', 'Hamstrings'],
    purpose: 'Corrects unilateral strength imbalances between limbs; places a heavy emphasis on single-leg stabilization and proprioception.',
    execution: 'Elevate the rear foot on a chair or box. Hold dumbbells at sides. Lower hips until the front thigh is parallel to the ground.',
    sets: '3',
    reps: '6-10/leg',
    impact: 'low', // Great for knee issues compared to bilateral heaviness
    unilateral: true,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
  },
  rdl: {
    id: 'rdl',
    name: 'Dumbbell Romanian Deadlift (RDL)',
    category: 'vertical_jump',
    equipment: 'dumbbells',
    muscles: ['Hamstrings', 'Gluteus Maximus', 'Erector Spinae'],
    purpose: 'Strengthens the posterior chain for aggressive hip extension power during the jump and eccentric deceleration during landing.',
    execution: 'Hinge at the hips with soft knees, lowering dumbbells down the shins. Squeeze glutes aggressively to return to a standing position.',
    sets: '3',
    reps: '8-12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
  },
  dumbbell_squat_jump: {
    id: 'dumbbell_squat_jump',
    name: 'Dumbbell Squat Jumps',
    category: 'vertical_jump',
    equipment: 'dumbbells', // Light
    muscles: ['Fast-Twitch Quadriceps', 'Calves'],
    purpose: 'Bridges maximum strength and explosive power; enhances the rate of force development (RFD) under mild resistance.',
    execution: 'Hold light dumbbells at sides. Perform a rapid quarter squat and explode vertically. Land softly, absorb the force, and immediately reset.',
    sets: '3',
    reps: '5',
    impact: 'high',
    unilateral: false,
    trackable: true, // Based on dumbbell weight used
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=A-cFYWvaHr0',
  },
  approach_box_jump: {
    id: 'approach_box_jump',
    name: 'Approach Box Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight', // plus sturdy box
    muscles: ['Total Lower Body Kinetic Chain'],
    purpose: 'The most highly sport-specific jump training available. Replicates exact approach mechanics and arm swing timing.',
    execution: 'Perform a traditional 3-step volleyball approach (Left-Right-Left for right-handed hitters) and jump onto a 12-20" box. Step down carefully to reset.',
    sets: '4',
    reps: '4-6',
    impact: 'medium', // Eccentric landing force is removed because of the box
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=52FZ-8tjAis',
  },
  tuck_jumps: {
    id: 'tuck_jumps',
    name: 'Tuck Jumps',
    category: 'vertical_jump',
    equipment: 'bodyweight',
    muscles: ['Hip Flexors', 'Core', 'Quadriceps'],
    purpose: 'Enhances reactive stretch-shortening cycle power and trains rapid hip flexion, essential for hang time.',
    execution: 'Jump vertically, rapidly driving the knees toward the chest. Land softly and immediately bound into the next repetition with minimal ground contact.',
    sets: '3',
    reps: '8',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg'
  },
  single_leg_calf_raise: {
    id: 'single_leg_calf_raise',
    name: 'Single-Leg Calf Raises',
    category: 'vertical_jump',
    equipment: 'dumbbell',
    muscles: ['Gastrocnemius', 'Soleus'],
    purpose: 'Increases ankle plantarflexion power for the critical final push-off phase of the vertical leap.',
    execution: 'Hold one dumbbell, stand on one leg on an elevated edge. Drop the heel below parallel, then press maximally up onto the toes.',
    sets: '3',
    reps: '15-20/leg',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=_XdMSO_qI38',
  },

  // --- TABLE 2: Upper Body Power and Core Stability (Attacking Mechanics) ---
  dumbbell_shoulder_press: {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    category: 'attacking_mechanics',
    equipment: 'dumbbells',
    muscles: ['Anterior and Medial Deltoid', 'Triceps'],
    purpose: 'Builds foundational overhead pressing strength and shoulder stability, directly correlating to spiking power and blocking rigidity.',
    execution: 'Sit or stand with an engaged core. Press dumbbells from shoulder level to full lockout overhead. Control the eccentric lowering phase.',
    sets: '3',
    reps: '6-10',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
  },
  explosive_pushups: {
    id: 'explosive_pushups',
    name: 'Explosive Push-Ups',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Pectoralis Major', 'Anterior Deltoid'],
    purpose: 'Develops fast-twitch muscle fibers in the chest and anterior shoulder for high-velocity arm swings.',
    execution: 'Lower the chest to the floor, then press up with maximum explosive force, attempting to lift the hands completely off the floor.',
    sets: '3',
    reps: 'Max',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=WbCVlWuHR0A',
  },
  bent_over_rows: {
    id: 'bent_over_rows',
    name: 'Bent-Over Dumbbell Rows',
    category: 'attacking_mechanics', // also acts as prehab
    equipment: 'dumbbells',
    muscles: ['Latissimus Dorsi', 'Rhomboids', 'Biceps'],
    purpose: 'Provides critical antagonistic balance to spiking; decelerates the arm swing safely and stabilizes the scapula.',
    execution: 'Hinge forward, maintaining a flat, neutral spine. Pull dumbbells to the hip crease, squeezing the shoulder blades tightly together.',
    sets: '3',
    reps: '10-12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=roCP6wCXPqo',
  },
  dead_bug: {
    id: 'dead_bug',
    name: 'Dead Bug',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Transverse Abdominis', 'Core Stabilizers'],
    purpose: 'Enhances anti-extension core stability, preventing dangerous lower back hyperextension during the arching phase of a spike.',
    execution: 'Lie supine with arms and legs elevated. Slowly lower the opposite arm and leg to the floor without allowing the lower back to arch off the ground.',
    sets: '2',
    reps: '12/side',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'CoreSvg',
    videoUrl: 'https://www.youtube.com/watch?v=4XLEnwUr1d8',
  },
  forearm_plank: {
    id: 'forearm_plank',
    name: 'Forearm Plank',
    category: 'attacking_mechanics',
    equipment: 'bodyweight',
    muscles: ['Total Core', 'Rectus Abdominis'],
    purpose: 'Builds isometric core endurance, allowing for improved kinetic transfer from the lower body to the hitting arm.',
    execution: 'Support the body on forearms and toes, maintaining a rigid, straight line from the head to the heels. Breathe steadily.',
    sets: '3',
    reps: '45-60s',
    impact: 'low',
    unilateral: false,
    trackable: false, // Or track time
    visual: 'CoreSvg',
    videoUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
  },

  // --- TABLE 3: Multidirectional Agility and Court Speed ---
  skater_jumps: {
    id: 'skater_jumps',
    name: 'Skater Jumps',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Gluteus Medius', 'Adductors', 'Ankles'],
    purpose: 'Elite drill for lateral force production, hip stability, and single-leg deceleration strength.',
    execution: 'Bound laterally from the right leg to the left leg, absorbing the landing deeply into a partial squat. Pause to stabilize, then bound back.',
    sets: '3',
    reps: '8/side',
    impact: 'medium',
    unilateral: true,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=xPt5eMJoikk',
  },
  lateral_hurdle_hops: {
    id: 'lateral_hurdle_hops',
    name: 'Lateral Hurdle Hops',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Calves', 'Quadriceps', 'Ankles'],
    purpose: 'Trains extremely rapid ground contact times and lateral change of direction speed.',
    execution: 'Set up a line of small obstacles. Keep feet together and bounce laterally over the obstacles as quickly as possible without losing balance.',
    sets: '3',
    reps: '30s',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=Ue3Kh3LKWQM',
  },
  t_cone_drill: {
    id: 't_cone_drill',
    name: 'T-Cone Agility Drill',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Total Lower Body'],
    purpose: 'Practices the rapid transitions between sprinting, defensive shuffling, and backpedaling.',
    execution: 'Sprint forward 10m to the center cone, shuffle left 5m, shuffle right 10m, shuffle left 5m back to center, then backpedal to the start.',
    sets: '4-6',
    reps: '1',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=6Yr2IQXUGGU',
  },
  block_jump_shuffle: {
    id: 'block_jump_shuffle',
    name: 'Block Jump to Lateral Shuffle',
    category: 'lateral_agility',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Calves', 'Hip Abductors'],
    purpose: 'Perfectly mimics a middle blockers movement requirements along the net during a rally.',
    execution: 'Perform a maximum vertical block jump. Upon landing, immediately execute two rapid lateral shuffles to the right, then jump again. Repeat to the left.',
    sets: '4',
    reps: '6 jumps',
    impact: 'high',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=WxRIFVAGh-o',
  },

  // --- TABLE 4: Shoulder Prehabilitation and Scapular Control ---
  side_lying_external_rotation: {
    id: 'side_lying_external_rotation',
    name: 'Side-Lying External Rotation',
    category: 'shoulder_prehab',
    equipment: 'dumbbell',
    muscles: ['Infraspinatus', 'Teres Minor'],
    purpose: 'Isolates and strengthens the external rotators to counter spiking imbalances and prevent impingement syndrome.',
    execution: 'Lie on side. Pin the working elbow to the ribs at a 90-degree angle. Rotate the dumbbell upward toward the ceiling in a controlled arc.',
    sets: '3',
    reps: '10-15',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=s9TBeBHmPf8',
  },
  side_lying_flexion: {
    id: 'side_lying_flexion',
    name: 'Side-Lying Flexion',
    category: 'shoulder_prehab',
    equipment: 'dumbbell',
    muscles: ['Anterior Deltoid', 'Rotator Cuff'],
    purpose: 'Strengthens the rotator cuff through a safe, planar arc of motion, building endurance in the stabilizers.',
    execution: 'Lie on side. Keep the arm entirely straight and raise the dumbbell in an arc in front of the body, ensuring the weight stays above the torso plane.',
    sets: '3',
    reps: '10-15',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'ShoulderSvg'
  },
  prone_ytw: {
    id: 'prone_ytw',
    name: 'Prone Y-T-W Raises',
    category: 'shoulder_prehab',
    equipment: 'bodyweight', // or extremely light
    muscles: ['Lower and Mid Trapezius', 'Rhomboids'],
    purpose: 'Establishes crucial scapular retraction and depression, correcting the forward shoulder posture typical of attackers.',
    execution: 'Lie face down. Raise straight arms to form a "Y" shape, squeezing the blades together. Repeat for "T" and "W" arm positions.',
    sets: '3',
    reps: '10 each',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=AEd5OglxwPw',
  },
  pushup_plus: {
    id: 'pushup_plus',
    name: 'Push-Up Plus',
    category: 'shoulder_prehab',
    equipment: 'bodyweight',
    muscles: ['Serratus Anterior'],
    purpose: 'Prevents scapular winging; an essential movement for ensuring healthy upward rotation of the shoulder blade during overhead extension.',
    execution: 'Ascend to the top of a standard push-up. From there, push the floor away further, actively rounding the upper back to spread the shoulder blades apart.',
    sets: '3',
    reps: '12',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=O9ZGIAeHzVE',
  },
  full_can_raise: {
    id: 'full_can_raise',
    name: 'Full Can Raise (Supraspinatus)',
    category: 'shoulder_prehab',
    equipment: 'dumbbells',
    muscles: ['Supraspinatus'],
    purpose: 'Activates the superior rotator cuff muscle responsible for initiating arm abduction and centering the humeral head.',
    execution: 'Stand tall. Raise dumbbells outward at a 45-degree angle (in the scapular plane) with thumbs pointing strictly up, stopping at shoulder height.',
    sets: '3',
    reps: '12',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'ShoulderSvg',
    videoUrl: 'https://www.youtube.com/watch?v=KPRGmnJcTBc',
  },

  // --- TABLE 5: Knee and Ankle Stabilization (Landing Mechanics) ---
  single_leg_rdl: {
    id: 'single_leg_rdl',
    name: 'Single-Leg RDL',
    category: 'knee_ankle_stability',
    equipment: 'dumbbell',
    muscles: ['Hamstrings', 'Glutes', 'Ankle Stabilizers'],
    purpose: 'Develops immense hamstring eccentric strength required for rapid deceleration and challenges dynamic ankle proprioception.',
    execution: 'Stand on one leg. Hinge at the hips, extending the free leg straight back to counterbalance. Maintain a flat back. Squeeze glutes to return to standing.',
    sets: '3',
    reps: '8-10/leg',
    impact: 'low',
    unilateral: true,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=XCj0o55jPG8',
  },
  single_leg_wall_sit: {
    id: 'single_leg_wall_sit',
    name: 'Single-Leg Wall Sit',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Patellar Tendon'],
    purpose: 'Isometric loading of the patellar tendon; clinically proven to be highly effective for managing and preventing jumpers knee pain.',
    execution: 'Sit against a wall with hips and knees both at 90-degree angles. Extend one leg straight out in front. Hold the isometric position.',
    sets: '3',
    reps: '20-30s/leg',
    impact: 'low',
    unilateral: true,
    trackable: false,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=V5HFnDrNMH8',
  },
  glute_bridges: {
    id: 'glute_bridges',
    name: 'Glute Bridges',
    category: 'knee_ankle_stability',
    equipment: 'dumbbells',
    muscles: ['Gluteus Maximus'],
    purpose: 'Isolates gluteal activation, ensuring the hips are neurologically primed to bear the brunt of landing forces rather than the fragile knee joints.',
    execution: 'Lie supine with knees bent and feet flat. Place a dumbbell on the pelvis if desired. Drive through the heels to push hips aggressively toward the ceiling.',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: true,
    visual: 'SquatSvg',
    videoUrl: 'https://www.youtube.com/watch?v=Vvn1gXMLbBE',
  },
  broad_jump_stabilize: {
    id: 'broad_jump_stabilize',
    name: 'Broad Jump to Stabilize',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Quadriceps', 'Hamstrings'],
    purpose: 'Teaches force absorption and reinforces correct triple-flexion landing mechanics to prevent valgus collapse.',
    execution: 'Jump forward horizontally. Land softly, dropping the hips back. Freeze the landing position for 2 full seconds, ensuring the knees do not cave inward.',
    sets: '3',
    reps: '5',
    impact: 'medium',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=8opxQHJBXOM',
  },
  ankle_sup_pro: {
    id: 'ankle_sup_pro',
    name: 'Ankle Supination and Pronation',
    category: 'knee_ankle_stability',
    equipment: 'bodyweight',
    muscles: ['Peroneals', 'Tibialis Posterior'],
    purpose: 'Strengthens the lateral and medial ankle ligaments, drastically increasing resilience against inversion and eversion sprains.',
    execution: 'Stand barefoot. Slowly roll outward onto the outside edges of the feet (supination), then roll inward to the inside edges of the feet (pronation).',
    sets: '3',
    reps: '15',
    impact: 'low',
    unilateral: false,
    trackable: false,
    visual: 'JumpSvg',
    videoUrl: 'https://www.youtube.com/watch?v=Y_IzfnlEE5s',
  }
};

export const EXERCISE_CATEGORIES = {
  vertical_jump: { label: 'Vertical Jump Power', color: 'text-orange-500', bg: 'bg-orange-500/10', border: 'border-orange-500' },
  attacking_mechanics: { label: 'Attacking Power', color: 'text-red-500', bg: 'bg-red-500/10', border: 'border-red-500' },
  lateral_agility: { label: 'Lateral Agility', color: 'text-yellow-500', bg: 'bg-yellow-500/10', border: 'border-yellow-500' },
  shoulder_prehab: { label: 'Shoulder Prehab', color: 'text-teal-500', bg: 'bg-teal-500/10', border: 'border-teal-500' },
  knee_ankle_stability: { label: 'Knee & Ankle Resilience', color: 'text-blue-500', bg: 'bg-blue-500/10', border: 'border-blue-500' },
};
